---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-feature-discovery-crds
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/node-feature-discovery.git
  ref:
    # renovate: datasource=github-releases depName=kubernetes-sigs/node-feature-discovery
    tag: v0.18.3
  ignore: |
    # exclude all
    /*
    # include only the specific CRD files
    !/deployment/base/nfd-crds/nfd-api-crds.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery-crds
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: nodefeatures.nfd.k8s-sigs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: keycloaks.k8s.keycloak.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: nodefeaturegroups.nfd.k8s-sigs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: nodefeaturerules.nfd.k8s-sigs.io
