---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: coredns
    namespace: kube-system
  values:
    replicaCount: 2
    k8sAppLabelOverride: kube-dns
    service:
      clusterIP: ${COREDNS_IP}
    serviceAccount:
      create: true
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
