---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: outline-dragonfly
  namespace: outline
spec:
  replicas: 1
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.35.1
  args:
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 1Gi
