apiVersion: v1
kind: Secret
metadata:
  name: outline-dragonfly-auth
  namespace: outline
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:jLbiRsBDGghJRLCn+r0uTk4cgOHF3LteHDkXJ7/khsS4shVt6OW7Yz+0CWM=,iv:ZofovrKl+yZp7W8ZsliO2tAx3OS1AU6s7RyI6qtHrns=,tag:dlXp+doJyjEnRMsngGuikQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0djMzRU5weFNwdld4NEw1
        OHN5Z1g4d3BGYmNkYlNVWUppVGQwcFdTbEgwCktwYnhTUGNJcW0rMEVibVdaNnFn
        U1I4WlhvbjgrYlVucEZadFUrTEJLYXMKLS0tIENmYWdod1FNcVJ5WDllRmJrUnhl
        UU1qeFJlbm1qZGpNRFZSQ21DejFRWk0KkY3H2IUjip7StRC6+3dTn6eJ5slVRvay
        yRzYvNJnQstIQHrcKaZr0My3Te9E65U3o84ylX7isKUkW/YTRSH0EA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T10:49:31Z"
  mac: ENC[AES256_GCM,data:3U9vvXPGPyOiktBKxfcOJjPBpldrK4GUfuOy/5ePjhQsnap/Is7Pl9aRsTME8ZAo/+IecMhiL9FEHxPDNei8wxp5zCuEUH9EygnLpKzBYFL9ptYpbI8+WLUvUglcaUPSqNEDPnneBhfEE4oVMlGTxJ+dxFC94W/zlm+rEfhDWmg=,iv:/yVxoRtZDcw6E/Ohu0UDPMEuGPDBWxfmsJbkszwQUcQ=,tag:5Wx/oaIB95K3FQMcx0QckA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
