---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: descheduler
      version: 0.35.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
      interval: 20m
  values:
    kind: Deployment
    serviceMonitor:
      enabled: true
