---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/cloudnative-pg/plugin-barman-cloud.git
  ref:
    # renovate: datasource=github-releases depName=cloudnative-pg/plugin-barman-cloud
    tag: v0.9.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud-crds
  namespace: flux-system
spec:
  interval: 20m
  prune: true
  sourceRef:
    kind: GitRepository
    name: plugin-barman-cloud
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: objectstores.barmancloud.cnpg.io
