---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    bpf:
      masquerade: true
    cni:
      exclusive: false
    envoy:
      enabled: false
    externalIPs:
      enabled: true
    ipam:
      operator:
        clusterPoolIPv4MaskSize: 16
        clusterPoolIPv4PodCIDRList:
          - ${CLUSTER_CIDR_PODS}
    k8sServiceHost: ${CLUSTER_DOMAIN}
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    nodePort:
      enabled: true
    nodeinit:
      enabled: true
    operator:
      replicas: 2
