---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cilium
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 30m
  values:
    k8sServiceHost: ${KUBEAPI}
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
      leaseDuration: 3s
      leaseRenewDeadline: 1s
      leaseRetryPeriod: 200ms
    envoy:
      enabled: false
    operator:
      replicas: 2
    nodeinit:
      enabled: true
    nodePort:
      enabled: false
    bpf:
      masquerade: true
    hubble:
      enabled: true
      metrics:
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          className: nginx
          annotations:
          hosts:
            - hubble.${DOMAIN}
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium

