---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  timeout: 3m
  url: oci://quay.io/cilium/charts/cilium
  ref:
    tag: 1.19.0
