apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-manager-sso-client-secret
  namespace: kubevirt-manager
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:+YYHFLjJp/ubDMV1CHmNifiOzoEgWLujVcnuJC2xXp0=,iv:dcxaiKfcIcUETkVTLtCVdxxMEhMdJerHox1pya0mcZQ=,tag:uW9blJ0hwvvfRYpQ8xTFBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT2g3QTVMZWNjSW5sZis5
        T3lCOGU1bExhMi9KNUwzTmlIWGZmSThSZHd3CnlmZDVqNDErdHZjRklEc0JpN2lI
        dWtFM2psaEdqVk9tWWRJTEZzZW9POU0KLS0tIGJGODBiQVE1ZnpaUWtLbFVyWDdu
        UjI1dEtBTDJybHVSeCtiTS9naXQ2dk0KMAo3eB2o317yAaeNCFc/FV7O+9OMGDD8
        xwExYRnTyzj6izG2XDlI376fUupkRwRUkRTm5A/jwWhLZ+frfKXg6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-18T18:16:19Z"
  mac: ENC[AES256_GCM,data:69r5Y2G6asym/xYtrlMZ/WsxOS1K0QTPEIcMyRL2KzFBvoRAM6ZKUctPUIQ52lONBee4eMv9OnDZY2QLAIQEVUDcu5VkKICtMofeE0T1nZdLses2L1898JRpLsjDckuKfReIxjV1hTuhfMW4jznTIGmHTmJCrCn5HtCG4a7xwq0=,iv:ovjbkYlY8HwXWp1guJPsBIu+9/oBd1RgwelTMlvzTQI=,tag:s/ecU9T34P7ioRyzPo8C+A==,type:str]
  version: 3.13.1
