---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
      interval: 30m
  values:
    envs:
      - name: UI_APP_NAME
        value: "Stirling PDF"
      - name: UI_HOME_DESCRIPTION
        value: "PDF Management"
      - name: UI_APP_NAVBAR_NAME
        value: "Stirling PDF"
      - name: ALLOW_GOOGLE_VISIBILITY
        value: "false"
      - name: APP_LOCALE
        value: "en_GB"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - name: pdf.${DOMAIN/./-}
          path: /
          tls: true
          tlsSecret: pdf-${DOMAIN/./-}-tls
