---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: flux-operator
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: flux-web-client
      valuesKey: client-id
      targetPath: web.config.authentication.oauth2.clientID
    - kind: Secret
      name: flux-web-client
      valuesKey: client-secret
      targetPath: web.config.authentication.oauth2.clientSecret
  values:
    installCRDs: true
    web:
      enabled: true
      config:
        baseURL: https://flux.${DOMAIN}
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: https://auth.${DOMAIN}/realms/auth
            scopes:
              - openid
              - profile
              - email
              - offline_access
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: flux.${DOMAIN}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: flux-${DOMAIN/./-}-tls
            hosts:
              - flux.${DOMAIN}
