apiVersion: v1
kind: Secret
metadata:
  name: flux-web-client
  namespace: flux-system
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:4agWEmGvGIo=,iv:6oYP+RQVra0mhJ3GZN52dCLgFmj3keCXHnKFN62bwC0=,tag:VpSa94tUS22tqg4JvlZrVQ==,type:str]
  client-secret: ENC[AES256_GCM,data:RSzIv8n8DwwXBVDg0eE2EtmPHl9wS8Z5ax0dANKNCTA=,iv:nh62YcE4fCAFiIspbLR6UfY4nvN2Rjum1O8MyNfMScw=,tag:3caAk6IYCvb6t/0LR2R8rA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaS83eW1yVWJIaXVldlFO
        bTFZU0xsM3FxK0s3V2ZObHlZNU1ySzN4aFJvCjVGdnpVKys2eGRNVVdWR2F0a0VZ
        d1VHRDUxOG01U2dPdjYxU2dJb2NNRGcKLS0tIElDWkdqMjVLUCs5NnpRYUc4eTVm
        RDgyQkFHbnorRXhMbkg5Smg2a2NZYW8KxbbLL5da6E6Zd/sWHLHMe65t72WfOkXA
        9H7oHFWayp12WH4N3hX6keP3CHH0mCb7N4jTbyfluxXy4I/s2d/cSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T16:37:08Z"
  mac: ENC[AES256_GCM,data:+nedUM9DDuyoCoHZMnyjsKZnjrLfc4CdRcJ+fKgjl+jXSLto2nBT6SL59sHgjdnbtoJJDIhY6zZun2OlAxC/ylvWG88LJyBBTFSjunZYqE6VGmWDVJwsNBFCxK8dKCuXmROzxIlSQMnUiolY693wR9MD/q5/VL5rr6Xi+SJKENo=,iv:WYeh9n6W7PKgbjcNvYI8mNxghrJAFWs0vgx0WXtqly0=,tag:iO70X4mGMPSr3IZ56xtNcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
