---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: gitlab-runner
      version: 0.85.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 30m
  valuesFrom:
    - kind: Secret
      name: gitlab-runner-helm-values
  values:
    gitlabUrl: https://git.${DOMAIN}
    unregisterRunners: true
    rbac:
      create: true
