---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: gitlab-runner
    namespace: gitlab
  valuesFrom:
    - kind: Secret
      name: gitlab-runner-helm-values
  values:
    gitlabUrl: https://git.${DOMAIN}
    unregisterRunners: true
    rbac:
      create: true
