apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-helm-values
  namespace: gitlab
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:U3gF/A7bWo+0iWmWy5+gLv5GLwabnGLbvm0erjoI8zx8XtAbyqgf3H1ubRJYQO3W58pjNZEB7UBz+nDWUzRAhLvGF1kA2JCxqm+/YoGCSBkveWTAzq4DQbLcNEAygbw1VbaC4Exws5GqAV7JG35bFmw6BJBTLMzH5BgcEDLfjqybbRbhSffZxlCF5eHZRIvN/8yK4u/VutOfjxo+3/gtuwDYLtIWXAhYm3EuWSxdcyePuIa79lNL5ykXwMUKJfWQS+l0g1uXbaJc1IY/aUy5W2i5OUL0nLPoNzAr0q/CJ8sdTBwLBzC98nq4yGLEZrlvyDVtTQBPhlQk3Kp8FPzSe/Q/b6BseZCEPhxUs5Dju22xomBg2bugBGOg9VpisaZpEs6bTTUFcqCpt7ThTP0L5CtxBl5Dm+ZcpsRG10Qvo5WVfJQ2qaHg4GuqBv6vArlA4+lPkoBlq9RTkx9XjEbKMQK237fFkOxFJI/2u8FXmU96V/FMjFhmFqTJcSHQ0PLlxJNTOCahu/D+DritsyxsYtp83wDdxVH8sTTZuDVXBMe8E1IvTmM4+olKzGJvJZjJSBMyzzgQCYluR+yf7QdpI95ntxpQlMfZGmeVwCZ2TwL/ON8CBJyX1l68NxHNlL8eOAHcZYY02boD+II4eLV/1Jeo5xi04E+u449kloaJRqE+4x6Zh+ouq0ocsBmaHfaEy3VYafPiF1giCXDrDrx5pCdoEnJxi/PueaYhbOHQOwDTJX5QKTtg68U=,iv:S/pK6nbB60hm/ZoAAs89uRMGfMGEl99j3L1wwQlTWGs=,tag:UjgH5waZOyt5c0ruLT22Sg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaEY5czUvV0dQYUdSVFhR
        UXM1elkrb0Y3bzZvTkNydkYzeW5uQ2Z2U1QwClFyYndid2hRQWJranluTEhCVlpy
        QkxncGU0dGRBd0trdVBnajZtV2FneHMKLS0tIDJ6cHRYOEYvVitWUkd3NWtkczhL
        NlI1d3VCWElVSFdwVDc1L04rRVkyS28KlDC22eHjcEpS2Rau1k/Hudd97mSk+Y6k
        v9GZD9dYXGoxwyVfoI8EDqwO5GC9yVjabh7534wX6b5eZWFhUY5oqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T13:16:17Z"
  mac: ENC[AES256_GCM,data:LZ/0JqfXzGRRq8+KoQVgSyygZ4jKIZ59vRrBHvgJ37cJ2mwleNZwv8xFWHI3InGbA4Ro6SoGL/k1+0UoMGgsa6apZ4WnRuRkuYRRnONa8w7hCunnBr+jND3Yf+zzbFzQHQ7HZDOBL6xWAk5D+G6MyopmuMHHV9UcWd9sCA6DVK8=,iv:ctDKIN+yxM/Yp9X3FcK+kvhd2+RH6F3rKe0qsMaftj8=,tag:cpTCulkSNXLZ/PJq0RUxng==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
