apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-helm-values
  namespace: gitlab
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:mFN27gdI1XMudGX3Vcq9h0uKexOJuBR3fQ9p9qxJ7o9IEu48BltmOkaixye2IGGQzIpylkBLEQP2ef8lVB+8ALQyz63jBVBxCi1gXE7WgDduSz6+U4ViD7Q+WfLAp36QFFuug8BYu/8+mH11aMvIA4PgICc1PO0OT1GTpK6x91wGl1RaO5ACB+mPs4ESh1s/R1KLeGofoqcH5K5sXs0jWLJd0gOlNYK/RJQQo1/xiD/voVXl7UBP+N+JydPoY20mTytPwupuEuyGO/GSunVjFG9DZKbN2nfwd7um17yz4mbavgFeJeYVy+1fhf/nfA2tP/21GxcbVcu6yYNPqQDse8lOt3r/7EiGpifWsg2XH29AOpISbwsHJFez7VnzpiGOlmWoLxSLJPrNdGur5wKCtgk7LaOdekvErRIdY1shDICa/49Z3tH+v39O1EiGXkVCDDxvCrcpTfkW2UKivu85GKh0AehrDdkWlaLGYexyP1W0bEzE40jRE7PjrKrZPHYKOp+jhHdGCsDvdlA6TuLCE6ZYnBlGsyoftsnQGUCNvbAb4OEFCBl8DfIVarijxQZzdj20gtI3eCBvW/xfL+MUUlv/M2eUl+cTvFsRepAiHlGoK+zS2Q8GjmKf3yDiIFiFJhi28aJ6wkDmf+ajtqWcjnzXahrifXMdmru6HWutpprSvLqFg8Ptfrb36XEi1PtIufT81JTakBwGXPJk5jazYB5b56JH9bpEwxys4qrBdW+2MvJUTd2ETto=,iv:Du9LAUrF1ySz6aYvzpMtfWTTLxRpk/Q3BRqtZOnJyQ8=,tag:xXnHN0nwWoRXMZndciookw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb0VqWXlWUGkzY1BwL3Jy
        Y011M05aOHVLU3NGK0tZMzJ5VS9IRWN5T2hJClA5Mlc1c1RxcWk4cHJ5aDFSZkVG
        REF4RTlybkUzaERMaHM2RVVhSFdzN3MKLS0tIFBvMDVEZ0NFTjZvV2Jzb1lRS0FJ
        UEFUcTQ4YnpDYjBISXVGOHhWMTJuMWMKkXG0YDWPYSu/aRCa0ZodXQL92jAgUeLQ
        MGWzfsGDYitf1k8B50D0ycosg1QW7DobQ8kvAsgmLsGFxceD84grtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:EQixsZX10u5heHZMUHDTb0anVoRksdxpBQTyPtYHs/kuG9869CjKZhM1UOvWz3osY6HQ/cGWEKhK01dqYVfrbGmKQNHLgLIUr7qBheHAIH/R2fC/JhSiizoG3vjFIziA77ugqFsstE3aFoCScpqQ22Kplv6RVDrIzr+LN868cLQ=,iv:FjpqgEAETsImI+JOmH8rcO9B+xdoBgc5RyZAw43WnZU=,tag:GWeYqqMyyeLIZg4EvuI+nA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
