apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-helm-values
  namespace: gitlab
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:YG6YwdXAncuoUfhra8DAHf9zu41G5YOfIJiNrjuLI5C2DHRinnkKxYydURIcYZyModHb03peCxkALZM0PzshAfakIs+7GgTMrKy4wxEZe4NzkHh2g6PW5zmezDmi72xMQSEws5EAPSwy2rPl/cFsOYQgly/6AHASi+OPzGpygQnJNT4X7zDxpTR8oMWo9Frgnubbbv+yofjgEFfDV/sF8dXapGVQpY2Yhsh4a1YcjKAO5jKLcEiI6PLWxclBcvCjTCrRynUY10gODSs1eODFzmGl0d3Dw1yVopg9BVFCJ0LA5FrNER/cBXEEz8czEurfJL/0tzocNchNVO+KHl9SjnaxIZSAxiZxVVKSYAR6ehUNS4FqRm64BCvnroRdJD/ecR+dRKQf+7sFSVKjEZLck2yvjdWBWQ8BpziVrZH2N7PgT8/TvJWmdLSnv3JxCiMoUCbJTZeay/8Nbp+kNAylufODQB/JKXp/+j1QhhCU8lDwwBns8QLXQnHT41OCXb+M+KX/WPyTyJHaEtO9grhtYWVJGoPVwy9iKW1XyfD6ERkqJSnF8aslIGOWxSzvPWGjugWk++Vnfx+j3+Fs3FuWDipy29PTj14xHdgtwt9dojbwiLT7JyL5+rLT8/T26qpPMI9nhBHBFuEWK344BGfDQGXlnXx5OTv7WggUcuIqS+CunXjP7yg6eGzFu9TGfaOItDCD3cSFSC/m2xAWe8S00kb+6fBv0a7BI5r61Rl9k3tBfUswLYNaWh4=,iv:KZxteqBzh9h3xVEhgF7NU+cIk0h8ApvslGvq6ZkOOb4=,tag:cdCYNFflNftk0cuM6VCiHw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZEtnUVJxYnZmeFdXUUc5
        YUdFMkRyZnJ0a1NtVXM1UmoxaEJBb21EMWhRCmFTZ3labm1CdzVpU1prTjhtcndo
        ZkZMWjA2eFJiZWN0ZFZSU1E5SWh6WTQKLS0tIFFQOHJraFFBVDJQNmMrOWJNWENy
        aHV5S3Y4bzRsTGpBdDQ2SE13K3lFUUUKhn6TmuwV7NP8BG5pG/bMHJ4ys5xD2pzW
        +9mgKI384PEJUR95Xi3/6dM9duyB6ZWURnTGqektx37R/vA8LQJ4vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:07:43Z"
  mac: ENC[AES256_GCM,data:oLXEhnWR7xASDTujVI0RAC4qYD8geUz7pia8CuDZkM7bhJTivNCDgbNGsluQzbho+fQGXupwl9OdN1e2+Zgqkl+o9nFa+sFgyjCP8axxG58UZ6fFhubVPT5EbHTczrV4IdZDYUgGgtFSrKLPUISjClHnsnsQ1gK7peiYRGHnXfE=,iv:j0t9IuQLHy/mi9ctZIV5wxC8VGfIVYzsej3Qq729brc=,tag:JAh42iRjYhuzfPLzo8xZ9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
