---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: rook-ceph
    namespace: rook-ceph
  values:
    monitoring:
      enabled: true
    csi:
      serviceMonitor:
        enabled: true
