---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-aistor-policy-gitlab
  namespace: gitlab
data:
  bucket-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": [
            "arn:aws:s3:::gitlab-artifacts-storage",
            "arn:aws:s3:::gitlab-artifacts-storage/*",
            "arn:aws:s3:::gitlab-backup-storage",
            "arn:aws:s3:::gitlab-backup-storage/*",
            "arn:aws:s3:::gitlab-tmp-storage",
            "arn:aws:s3:::gitlab-tmp-storage/*",
            "arn:aws:s3:::gitlab-ci-secure-files-storage",
            "arn:aws:s3:::gitlab-ci-secure-files-storage/*",
            "arn:aws:s3:::gitlab-dependency-proxy",
            "arn:aws:s3:::gitlab-dependency-proxy/*",
            "arn:aws:s3:::gitlab-external-diffs",
            "arn:aws:s3:::gitlab-external-diffs/*",
            "arn:aws:s3:::gitlab-lfs-storage",
            "arn:aws:s3:::gitlab-lfs-storage/*",
            "arn:aws:s3:::gitlab-packages-storage",
            "arn:aws:s3:::gitlab-packages-storage/*",
            "arn:aws:s3:::gitlab-terraform-state-storage",
            "arn:aws:s3:::gitlab-terraform-state-storage/*",
            "arn:aws:s3:::gitlab-uploads-storage",
            "arn:aws:s3:::gitlab-uploads-storage/*",
            "arn:aws:s3:::gitlab-pages-storage",
            "arn:aws:s3:::gitlab-pages-storage/*",
            "arn:aws:s3:::gitlab-registry-storage",
            "arn:aws:s3:::gitlab-registry-storage/*"
          ]
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-aistor-policy-gitlab-runner
  namespace: gitlab
data:
  bucket-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": [
            "arn:aws:s3:::gitlab-runner-cache",
            "arn:aws:s3:::gitlab-runner-cache/*"
          ]
        }
      ]
    }
