---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline-minio
  namespace: outline
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: tenant
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 20m
  valuesFrom:
    - kind: Secret
      name: outline-minio-values
  values:
    tenant:
      name: outline-minio
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 10Gi
          storageClassName: ceph-block
      metrics:
        enabled: true
        port: 9000
        protocol: http
      prometheusOperator: true
      certificate:
        requestAutoCert: false
      buckets:
        - name: data
          objectLock: false
          region: us-east-1
      users:
        - name: outline-minio-user-outline
      env:
        - name: TZ
          value: Europe/Zurich
        - name: MINIO_DRIVE_CHECK_INTERVAL
          value: 5m
        - name: MINIO_SERVER_URL
          value: https://minio.outline.${DOMAIN}
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://console.minio.outline.${DOMAIN}
        - name: PROMETHEUS_NAMESPACE
          value: "monitoring"
        - name: MINIO_PROMETHEUS_URL
          value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    ingress:
      api:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        host: minio.outline.${DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - secretName: minio-outline-${DOMAIN/./-}-tls
            hosts:
              - minio.outline.${DOMAIN}
      console:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        host: console.minio.outline.${DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - secretName: console-minio-outline-${DOMAIN/./-}-tls
            hosts:
              - console.minio.outline.${DOMAIN}
