---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    crds:
      install: false
    additionalLabels:
      grafana_dashboard: "1"
    grafanaDashboard:
      enabled: true
      labels:
        name: dashboard_name
    rbacProxy:
      enabled: false
    serviceMonitor:
      enabled: true
