---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: 1.2.1
      sourceRef:
        kind: OCIRepository
        name: dragonfly-operator
        namespace: flux-system
      interval: 20m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    crds:
      install: true
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
