---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: gitlab-aistor
  namespace: gitlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway-system
  listeners:
    - name: gitlab-aistor
      hostname: aistor.git.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: aistor-git-${DOMAIN/./-}-tls
    - name: gitlab-aistor-console
      hostname: console.aistor.git.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: console-aistor-git-${DOMAIN/./-}-tls
