apiVersion: v1
kind: Secret
metadata:
  name: aistor-env-configuration
  namespace: gitlab
type: Opaque
stringData:
  config.env: ENC[AES256_GCM,data:QRVcjDWpHZlRZrBZjAgJ7GisxIJf2HsRPhBoit/4Zxx408ynH5Vw1xTfZEo069TdD+y566rRA+gX3E0FG4u10xRyq9KNk9jELtt3ofKDW1pcFpEOnLYOvYPV3DhIBOW4/eBIxyUvRiwLDYQ0tfwV281E8nQTjkcMGDlrGYJwuxT12dGMA6A17M7kl7daDIb/0XeCJlZNghXJmXjWyVC8/hrSgn2D9g3ZP7rO/LrVCCBFCJs18NpKL9/+lhAlz3ZvyJ2CisctqrW5A6QjdI22SFk4OHaLTYftqq8BawdUdxzzararoXCt3OeL2XdnJeNXl7GEUvhPacsFqQ7Fk1X0+fJY48itHHcOOaPTI31iGkyZCWh+rEmg2MF3oS8EQUZdMucCZKO8Wcd/i6/PTDNYfnU9oXOw2N5hRrIwgQOvFEPoUiHvMemUuLvZ5DF2nseRzGELgxMoG+40QVDcKFeJeggDa1OzqzDZtuc0qN+I8Eiv3E5iDn2rnXZu4Bd80lrBy/+sxABmIsHoktmXOxBNHzab0z6TS+oN+JPk3424NlHPDAvOtsZR0j3T/Az3/nkOrPFoOhVfAqtGQ46H10ovQXispRJXh6CsrUrvfuSEZDgH2QCNBN79024OahljiVTd0iLwaY7wSBSj1HiKVnwVJxy9uZprqayVhKn5AywLbUaFPI07Ym5ETj/Am0d9oZF8VAro2MGg0J7QraVFTZ2IdqBdarQDmdvuUMXeri0QYChEbclH26APWII9jCaKA9RMe6sAAGA10kMIwizBxylDFZ3O53c1j+js7DRQwmitS6aMPIuolRVbTdJxiCLdDpkCnLP4A1QIIMabHd8tNWfHlS/vh0h9apUK8hYYZ5sh6YhEyXQVu7XNwJTDa6CmMLIJAOraqOYJ/SqoSUJH/r/SUtiixCY1azNBlvzTolfk5E9rVkzgjZxV2tXY+um8M5gUI4bwonLjdbkFhn5pbruXFvPZSydLuiwD/zj7DQ17VimPGwMxVg==,iv:zKeL75Y6jaiM+L5+o5KR/JFNvS1vHfJjWANOF9eJ2Z8=,tag:ZcRmm31Q4Yfyx7Q2yXf/bw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V1NqVGEzYmhLVmw1amlY
        TTRtZm1FRFNZNnkxYTM4Yzc2NnQxdXk4ejBVClhxU3Vpc24ra1g4RmNVaFV5Yi9n
        S2wyZ0JLRnZQREEzcXJiNlZZMFJMTVEKLS0tIGVZWlRGaVZrMTlpdksrdmxXTjFJ
        RGNPZE5UZ09MNFYwbjVUWTI3RTRNSmsKp1k5+XlfPYX9i7bP/74i28yv7xvd5gA+
        RP7tvQFYLYJ/XLcac4Y4MXL4z4VMVwqRENDjqaqqwYUMnHbd5Oxe3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T11:32:03Z"
  mac: ENC[AES256_GCM,data:cymd/gmnvhlZ4SfkawAIL3U169ARnjYP80cqkNrmbrTkRiXN/daNPqTxBarC00q/qMUfP7TolKdaqDljQNoRnlHEK8M/iaFRcRq10+gjb0ELeWhMUle4+bPpBpxKpYXB5HegU0RkROEWYO0nnvAJ/yklesSAmKFTEM7IPywIxnU=,iv:F0SaTT9vTjq375MAkgQILOOj1N70QhUmiIEgL7rfLf4=,tag:o7xpCxLLdv7+ytdG12wH5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: aistor-gitlab-user
  namespace: gitlab
type: Opaque
stringData:
  ACCESS_KEY: ENC[AES256_GCM,data:CIG27/dh,iv:xVLHubVL2cHE6i9ReSkDEwnU071EBIO0TfjJ2GLh8o0=,tag:2eO9CSxI09x6i4WlYkM9Eg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:3U4Hy6mmnlAI9RM4Vw/qgIqb34IDsQ3aJvHxsmJUvgejm3frpHf01nQTTxXJ5GXtzLEJXWWFKehuwfPUWpjMfA==,iv:5/WleYS9CcbM3CubCMOIVdxKwVRvYwlzXM/oOYjqc4k=,tag:ej1Mx+/XvU6ajMFuYYgmMQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V1NqVGEzYmhLVmw1amlY
        TTRtZm1FRFNZNnkxYTM4Yzc2NnQxdXk4ejBVClhxU3Vpc24ra1g4RmNVaFV5Yi9n
        S2wyZ0JLRnZQREEzcXJiNlZZMFJMTVEKLS0tIGVZWlRGaVZrMTlpdksrdmxXTjFJ
        RGNPZE5UZ09MNFYwbjVUWTI3RTRNSmsKp1k5+XlfPYX9i7bP/74i28yv7xvd5gA+
        RP7tvQFYLYJ/XLcac4Y4MXL4z4VMVwqRENDjqaqqwYUMnHbd5Oxe3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T11:32:03Z"
  mac: ENC[AES256_GCM,data:cymd/gmnvhlZ4SfkawAIL3U169ARnjYP80cqkNrmbrTkRiXN/daNPqTxBarC00q/qMUfP7TolKdaqDljQNoRnlHEK8M/iaFRcRq10+gjb0ELeWhMUle4+bPpBpxKpYXB5HegU0RkROEWYO0nnvAJ/yklesSAmKFTEM7IPywIxnU=,iv:F0SaTT9vTjq375MAkgQILOOj1N70QhUmiIEgL7rfLf4=,tag:o7xpCxLLdv7+ytdG12wH5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
