---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mimir
  namespace: mimir
spec:
  interval: 1h
  timeout: 3m
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  ref:
    tag: 6.0.5
