apiVersion: v1
kind: Secret
metadata:
  name: mimir-bucket-secret
  namespace: mimir
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bpc3+8YtJYDl0/mce5Y/1klJ/wuuKDui0Lt2VQ93VeI=,iv:ZVR7iceLBajm7Yv7hgB7CdDmYaJXIPjJTZ/EiyKlij8=,tag:FB+Fnhh1aZZxxLDvhb37tQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XCctz0a8oeFFL6+lRPU6vdSkKBVzFMlc1kgkb0giArQ=,iv:DBGOVqgqoQFj0GsGofWJucmUypq17ZT9O/K0WJQHyj0=,tag:hOg+lBvAnWN/baBd7goE5Q==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWTdkWm5BWGN2d2pOMDRa
        TkFaUW1JbEJuTVhUbXpkSm1ERjk0anJkU2tBCnVaOFRKdlRzL1NKN3E1eDZReU14
        aGY2MzYvVFRrYjhmVlUybTE0b1Uxd00KLS0tIERndmx2cXVRaVcraS80REVGSFpV
        QU96WkZMdnZId0NQMTQwUEZYRWV2b28K+38KhyWm3FAJ27Um1I32WDARy6HjcIAh
        FtbFHuVmLZOoz+gqHA3KsQqPR5VrmffjzVwkMZJCZ+0sV+RdXa7EFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T16:03:57Z"
  mac: ENC[AES256_GCM,data:62BRX6IMh7Gnw1ffnoB//dGEvU0epS3BJiWX6WSS1lN3IYywo/CnDk9UfqR74ByouhCcqOVMfOdxMfROWUbLT5rI+US9VAAeP5HVYQGaEfIgNsWJbQkx68ajxuGc7k0lz8F9LFAPKRWvLOJcn0j/etksRj2cgrc+WYsFivC50Jw=,iv:cVh6AtcvzqCczhiesFOH5rCEZRYd1DR44X8gtWdoExY=,tag:fZSxR8F8qGRIYhAHKmLHTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
