apiVersion: v1
kind: Secret
metadata:
  name: mimir-bucket-secret
  namespace: mimir
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:l6a2DE4r5fGkeeIqAeZ2uVcCcToVr5vFRIU7j57PsvH3w0L/9yGK2MZUicuP8vAAt/RY2hdxQ4MArwEE0r4hkw==,iv:uWsh03ZYswsuiCY3w7tqUhBy3t/f2P/41f6sh5nqqPw=,tag:9cyEDcoQy3IQmyLwFEWVow==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u/GkyIZtlJp1MWTm2PAubluh9UiCxt8XuXvd2pBGzg3LxOkUlSX9kW/V4rTRLH9bnoNQVvL/MueZTVG/uldMEA==,iv:cq3AFq/TSinIbNuTX6ViXEjYP0y+XPLQwvVBMRZxV4Y=,tag:1yP17n8BPW8LWkYjzZsfbQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXlLcnRBVHlFNjVtN29D
        U0VlRkJqODFJTTVmNXd6bWxSN0FJcnB0S1NzCm1wc05nU1IyY2wyam5kLyt2VU9O
        VUltb2libE5EZU1hUmVCRUFBWVlISVUKLS0tIHdyUldRWHdrMnZpZEJNSWcxT0RM
        MFhTSjk4Zm1DRDE4QlZnZWFoNytSR0kKjSoeN2Ot7jO9IK9/qYpVnNpxcxhmf9Pm
        o/IIMJKcyAOhrO1UJog7BlRIRbd+McBXmVECRWJvk/i1B+5kTfDhUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T13:17:18Z"
  mac: ENC[AES256_GCM,data:73DJogUrbEDOg8iiHxVZNTz4YLpHhVStRR7pkNlEjey6pQNqU52/TvS0ue6DTZ2AQr0GsoHklRyqdGm8tqTIW46gTMGm0lDz+kNWz520OEjmlmemiFIUlnhttMm35NQHqMaYMTx0jaUNTO9RjIApg6iJTM3ZGdHGxc6lkIQdI4Y=,iv:GwWXRKWgEJiSLZozYCQt+HYN+Ww6Rb6JK9Qw832CnjU=,tag:dENEFyFBgEsbYDD7zpSt7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
