---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: jetstack
    namespace: cert-manager
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    installCRDs: false
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        namespace: monitoring
