---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/coredns/charts/coredns
  ref:
    tag: 1.45.2
