---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 20m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    crds:
      create: false
