---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
    namespace: cnpg-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    crds:
      create: false
