---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  ref:
    tag: 0.5.0
