apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: vaultwarden
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:xY9UmQAP7vWq5yEfb+/qiiocptEnXyUmHoZZNE3PETg=,iv:CkUo+pstVGbIsUhfMjZJ7NQmKYNnJfaRMRNNwwiJwmc=,tag:GgSug+99jZMxXxWFdqn0wg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:vdsyTesB406HcfTRSFVGO6a2WkICoqebRvmBReQ3X8k=,iv:L9GffPnJG/dzxqVzDlwIb1TGFOjHXJvley6f2ryXdn0=,tag:CQ5AS4mBVi4j9UPIZuJNAw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVHI1c0JTNUVDbFRDTEN1
        bHVsNjNKbjIxaEJTSStNQ2N1NnU5Ujd6aURvCnh3ckRwTmVoamQ3UzcwdTJIaGNB
        YnpCRnBhYWRyQ2I4QlZhU2w0Y1ZvT2cKLS0tIExsaEgvanFKeHIwR3FoWlU5Z3Ux
        Uk1RQUp2WThWaUlDSHJlV2Q4akx0WGcKbbKFQUh21DQe6I1MUno8MNF3eht1vttV
        uma/M0ni64mRFRo/njx9q9k1QFkjbqA44MmFX7YSBDXn0HJzrexv1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T15:06:26Z"
  mac: ENC[AES256_GCM,data:/8Cc+dtrGF5/2C5QRbiM9j9l59lJpmj5s1dscwwhkCngRTNqhdHVQF2I9BDazvGnMNXgd/U8q3kdsGuIC2CIvZJSB50l+qEX28bzRr8hM1fPxyoQyLaIjktVdH+N0MSZEPvEMywsd1sdUkrTUZOJxxWvnkAbNqQ3gohEraOOlRg=,iv:xVqdG+TH8nSZrZ3/9z6S0795ojRdmWKWetyh8XaJLmg=,tag:sRkLK2UoX0iyXGXH2M0exw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
