---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
    namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    prometheus:
      enable: true
