---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  timeout: 3m
  url: oci://registry.k8s.io/nfd/charts/node-feature-discovery
  ref:
    tag: 0.18.3
