apiVersion: v1
kind: Secret
metadata:
  name: outline-server-secret
  namespace: outline
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:PoM9Q3y/naD+HB7yaIqjtFGZY2Mr7M2Vf1FdBot+YFgo6+42F6bzCd3QmxacydPAWRSRaLOGL+cNB6VN1mUSfw==,iv:5XNr1r24kz9qqXycvnhMf7kgqQq8dOEiS8djthHX/6M=,tag:Cuy0freSfQVyNKa9xr18YA==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:aqOtslXHgt8n6xArA6oac6AaktPmtUdakLDGg22KLE41cLkfdoJehQJXSDWgDETH+d/+ZSEwqrQTGWGn0GLw/A==,iv:AwjoxHbGeScAa16LV2cUJCG7c46fO0fEDx2Yme5y3NI=,tag:m9q9uwVJuxeypRJRCkiZtw==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:0Hm34mQrjtreQzjB9bN0Cyr5MRVioJwMhPf15cj+FeF+E4IJPWZFmmYkQUSkPuvnEGHIxpIIvVBI6rw141Kxs3A562mVG8riqhVtn7Q+Gxnx4PUn/+B63icY,iv:I2RVjWRtB0p9duyKaz6OJV88v2XJzR5L4d9Cv2+IMRw=,tag:wthhaj+tr5bwvwooGP8Mtg==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:nNpfU7xUhw==,iv:BqBj3eYFfwNBya+VARqa3bVFAQIbyyU6iMvR1MVdvk8=,tag:SHbAhKVlOS0Wcc1pVYy5gA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Z/Rpax8GhUOgO3dqRrMKlJnD9eSCmsq13dvmoSUTOlg=,iv:6BPJU0xSK8yR6ecd59FyotbVXMmxFq4rMd8qaFBGPuE=,tag:8PehtWnQ5O7FWqWhiYbKKQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:HHE4Em17plP7v78Iyg==,iv:FwuV72vYMrUC3PPbhq5vQtxfG4DrbHCQayPkeUq4rKQ=,tag:068tI4zWwLayugYNWrRkCA==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:NiDP,iv:SPlvSd1xuIGpiMdIycp9xBPQ/8UFxy/pBIeUl/aYIWw=,tag:2vTB7xsuIOaCd2OVL59jzw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:ecCDDC7VCFBEU65uvecZKQ==,iv:jGFmVfU1aH4rSvOK+81m3mRhSWE/PT5+/mlCyK9yzKM=,tag:2GCwuNzP7uEvCl30Z7Bh5A==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:ApHsPSLOTvkIgfHLR8ltHBnhEIrfYOSQRtKuAK5FoKmI9bg9oMo3dofmYImb8xvVSROfZfuxb9K/WHd/KVD/mpwHVkDZTVt+EI0W21s9zaM0tUUPJuLdNcvComFRyx2yF+XXUUAwZVWNuZstFkOLl1s8pa/VrcoM0Y9qm+EPnmM=,iv:as6bpHyKwKFo1IWWHFXSq+1WOYw2TOW67tIxPKYwo1s=,tag:QIe2z6zRE6Vnkg7gqfin7g==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:n7EPE+o9+KAUnWbub7JXfQ==,iv:C0Ir1bC45HQjZNjjjVXOcjRcEZuXw63c8TFI3e8NKpY=,tag:NTFGepoRB3Lkg/MM3dMirw==,type:str]
  SMTP_REPLY_EMAIL: ENC[AES256_GCM,data:KEMPKxiZ7Z3srtHTJHuKuA==,iv:f8j3QoOE2bVvIEr7T5ZRtQ0vWBytrpdog4C6wp3V6kA=,tag:5uC41lhiWNwXH3u6MrpdwQ==,type:str]
  SMTP_SECURE: ENC[AES256_GCM,data:H8xqKQ==,iv:GVmJ1DVbz7FZGaGqt8S1g7wBZu5Z2RYL/Fo7CHQIu3Y=,tag:ffWcZ+2FMj02veX44l2V5Q==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1Q1cnFLbjdXQnNHUzFB
        dUJjUkhlZDNId1U2QUsrVVBieWZtTVVia0dRClh6SnNwSmEzd05HL1FtdmdNb1Iz
        QWF1SUJtOXdnNk5CUmgvQnMrdVg3VkEKLS0tIHl4L0R2WHBZVHJBZHhPc2JDL2VQ
        MDJGZ2ZJUU1SaGZ3ZE9LVHQwOXF5UkUKaVYRC8M5MjLYdihp4yD1p3r/IMjnM7gN
        +XyH1YFH4VqOvhuog9cIrY0h88AeNrNCvxrAn80oCTpPzYhPxVSp2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T20:12:44Z"
  mac: ENC[AES256_GCM,data:NnF1HjzWKN0hZMSXHTKxKuEpqNKlqime/F+T31asUWmrljUCtjQ2NEhFK8WAt/KX+RHXZk5o5Zd5l9aUHxzi1u3K/1gWW+2Hr/bAL+0cRyUQMaFRq5AU56mydThhIzOWdt2iDte8XNEnkxc3eKLjmmEOjfffCI6Oix/aPVi2XJc=,iv:BpEqeq69g/jgxanJIflxuRYO1Pwf3ZdWZKaUPz3/5eU=,tag:020/zg0RnmdN+PupqT05IA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
