apiVersion: v1
kind: Secret
metadata:
  name: outline-server-secret
  namespace: outline
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:I3ncCKCjSyu7AA3I0a24L2KqWCDW6BBu6bkrJHJAgT9tTVMhmD1Wz4jxMkbjDUUgbAPy22xFVwRHgsQjXBvd1w==,iv:PrHigQ6f6DnlSNZxKDa2e8LsOak+EbDfQhm9fySjnh4=,tag:MsNVL95eYn2rtiuhN7JztQ==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:iWBSrXBIjt6sxA+pWoIN2QgjV8UDp6p3RrT1yi1c0RWzJK8JvVWqM3exw1wpkmG1N4l1HYFih8vN8lSUDcmNPQ==,iv:3uUQGPze31fKnvugVkhUXyKfHfc0D6g5iCwnaH3Afe0=,tag:74XaZ6Z8ZOGVvOHDusJb0Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+9d5slCXKg==,iv:kaVKRwUQUnK481SWEiJJTf6iGIy3/AI+/3kf4bGcfMo=,tag:MQV2iXIjYGDUEojbbEKwJQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9J/+k7YaGUDizfOpSRHpDkBM70CbkzAXnSZFrYOfaRT+mI8lzEdhDbbrActUklhCvBBadk1Ed6RyLWKfAnhL5Q==,iv:TFvCABCsRbS15IteaXcL4XpimfVA9GOc7NVIi+EOuY4=,tag:xy2m3zR3gkZZlo4x7LnOxg==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:1M6dSn1qRQ==,iv:kobfmdO0JEzjoEug73Wy29CjfCNnx3ilFOLOMEo2qgY=,tag:kV9ttFZ0GrwZ+Ia8icktyg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Qh/GcxaAvohtG39D/FHUjHgbcv5atl/gnUPuCe4dHdc=,iv:b2W03XyiQT2J1+1IgEYmCJoC3GueMXxMlgxvbgN8wQY=,tag:VJ7xbDubxu4OeQ0DFoZmcA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:ryTGrP8qbjIrBrvl7A==,iv:H6si4DTowiwILZ4liBIvd/jHCni+TOl7FKJKmn9zkuc=,tag:xLJvkfp3KO9ZCneYnR1epw==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:5RM7,iv:19lUES3xsxXTCswuKEG3GGFP0Ye929aulVCNaiy8I1o=,tag:0PrbhnIYpQK9dPzRqHUq+A==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:WY/KClOZnf8WpigNe6x98Q==,iv:m50FowD9OxckR/+FZTVhTpzy/JMgMFqpq9FS9AysIIk=,tag:7Psqga5vN1cCTAFxskEdVA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:0YJRpMRV0V7K61ikctvR+8IMEg6WlYtIvZeaXRQcd/q8AN2oaGwpdkRa6ncNYT1vKmdGL+yHlAsPRWn9VlFz6nTpY+Pn1lk7CTxn1o3Lqevf8DiPydThXBBx/5boIFlo1VhTtXYoOzrYHvuDbs9R5ywSCCPleFiNTHh8aeJzDZs=,iv:cZf3aOip55C1bZiXECD2pVDMqL5dDeskb808oXAbD0U=,tag:0ZCvO/UrhtArPiIch4lEYw==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:DYXmWCVJv3YFFk5m+3CjyA==,iv:zXcu8CpormsIobFIHCoZkC32SJn2844sQ17aVh5rm44=,tag:Cc1CyryhHGDNyHud84CjJw==,type:str]
  SMTP_REPLY_EMAIL: ENC[AES256_GCM,data:+WVl9ayMxD77X5HLkx2xyA==,iv:arKLUYJPhJz+QeUwJGHCqFqC4oaE5J62NjT1AhQDl7w=,tag:zXKDr5yNOcqmLn0IRnH6lg==,type:str]
  SMTP_SECURE: ENC[AES256_GCM,data:4Rsqlg==,iv:yPUOww4bL2iZaXnpLEU5o520E0Q2wr040qiGGy+CCo8=,tag:g0jBzWZB74Yr3tKoBjEFZQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFZGVWs5Y0VkdCtyb1hV
        UGk1SE1xRk5hM3ZZZjdBUFJlZ1hEeGZ5VWhnCk5vM1lHR3cyd0dCbUluU2t4Z0FJ
        S2RsV21DWFpFSWpuWkk2ZFJRdXo3bEUKLS0tIFRlQytEUm1xWnkyUm5TN2dmbnlj
        RnUxamRGb3Q2UXA2NW1SeXN3eGVucUUKz3YjpQUTqdMpRWn8CS/NUl4eAosNtN/0
        MzWdJ05YjUzoUIEmxDe9iRk86gH/5AhVhNW1MkAb4+F0I5QRtobhGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T15:47:38Z"
  mac: ENC[AES256_GCM,data:dx61xoKAXY9Q8UO9nukeZEIgj1bSOPmLa29igEfiz0GFaLpe5kKMF/kMiV3pH8dx7clbPzMw9p8pcILyBuykQFr9QqseMpwHGY9eN3cxDraD45IYp949CHBq5n7M+N3LujMf4ZSH590+TRmbO7pGaXFyHXvq6Tv/+ciLgIBkN+4=,iv:TIjgm0ga8YVGCdjlC8p759CUmtKd0bJ16JH6rHWVp10=,tag:u+Me4oRFH9hpoREWmXrkog==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
