---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 20m
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        enable-real-ip: "true"
        force-ssl-redirect: "true"
        ssl-protocols: TLSv1.3 TLSv1.2
        use-forwarded-headers: "true"
      ingressClassResource:
        default: true
      service:
        enabled: true
        annotations:
          loadbalancer.cilium.io/ipam: ingress-nginx
        externalTrafficPolicy: Local

