---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  timeout: 3m
  url: oci://registry.k8s.io/ingress-nginx/charts/ingress-nginx
  ref:
    tag: v4.15.0
