---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: rook-ceph
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.17.7
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 20m
  values:
    toolbox:
      enabled: true
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        host:
          name: rook-ceph.${DOMAIN}
          path: /
          pathType: Prefix
        tls:
          - secretName: rook-ceph-${DOMAIN/./-}-tls
            hosts:
              - rook-ceph.${DOMAIN}
        ingressClassName: nginx
    cephClusterSpec:
      cephConfig:
        global:
          bdev_enable_discard: "true"
          bdev_async_discard_threads: "1"
          osd_class_update_on_start: "false"
          device_failure_prediction_mode: local
      dashboard:
        enabled: true
        ssl: false
      network:
        provider: host
        connections:
          requireMsgr2: true
    storage:
      useAllNodes: true
      useAllDevices: false
      devicePathFilter: /dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_.*
      config:
        osdsPerDevice: "1"
        cephBlockPools:
          - name: ceph-blockpool
            spec:
              failureDomain: host
              replicated:
                size: 3
            storageClass:
              enabled: true
              name: ceph-block
              isDefault: true
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              volumeBindingMode: Immediate
              mountOptions: ["discard"]
              parameters:
                compression_mode: aggressive
                compression_algorithm: zstd
                imageFormat: "2"
                imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
                csi.storage.k8s.io/fstype: ext4
        cephBlockPoolsVolumeSnapshotClass:
          enabled: true
          name: csi-ceph-blockpool
          isDefault: false
          deletionPolicy: Delete
    monitoring:
      enabled: true
      createPrometheusRules: true
