---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: rook-ceph
      version: v1.17.7
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 20m
