---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: velero
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 30m
  values:
    upgradeCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
