---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: velero
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    upgradeCRDs: false
    cleanUpCRDs: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: kubevirt-velero-plugin
        image: quay.io/kubevirt/kubevirt-velero-plugin:v0.8.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      features: EnableCSI
      backupStorageLocation:
        - name: minio-backup
          provider: aws
          bucket: backup-velero
          default: true
          accessMode: ReadWrite
          credential:
            name: velero-minio-backup-credentials
            key: cloud
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: http://minio.minio-backup.svc.cluster.local
            publicUrl: https://backup.minio.${DOMAIN}
      volumeSnapshotLocation:
        - name: ceph-block
          provider: csi
          config:
            snapshotClassName: ceph-block
        - name: ceph-filesystem
          provider: csi
          config:
            snapshotClassName: ceph-filesystem
    credentials:
      useSecret: false
    deployNodeAgent: true
