---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: velero
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    upgradeCRDs: false
    cleanUpCRDs: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroBackupFailed
            annotations:
              message: Velero backup {{ $labels.schedule }} has failed
            expr: |-
              velero_backup_last_status{schedule!=""} != 1
            for: 15m
            labels:
              severity: warning
          - alert: VeleroBackupFailing
            annotations:
              message: Velero backup {{ $labels.schedule }} has been failing for the last 12h
            expr: |-
              velero_backup_last_status{schedule!=""} != 1
            for: 12h
            labels:
              severity: critical
          - alert: VeleroNoNewBackup
            annotations:
              message: Velero backup {{ $labels.schedule }} has not run successfully in the last 25h
            expr: |-
              (
              (time() - velero_backup_last_successful_timestamp{schedule!=""}) >bool (25 * 3600)
              or
              absent(velero_backup_last_successful_timestamp{schedule!=""})
              ) == 1
            for: 1h
            labels:
              severity: critical
          - alert: VeleroBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups
            expr: |-
              rate(velero_backup_partial_failure_total{schedule!=""}[25m])
                / rate(velero_backup_attempt_total{schedule!=""}[25m]) > 0.5
            for: 15m
            labels:
              severity: warning
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: kubevirt-velero-plugin
        image: quay.io/kubevirt/kubevirt-velero-plugin:v0.8.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      features: EnableCSI
      backupStorageLocation:
        - name: minio-backup
          provider: aws
          bucket: backup-velero
          default: true
          accessMode: ReadWrite
          credential:
            name: velero-minio-backup-credentials
            key: cloud
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: http://minio.minio-backup.svc.cluster.local
            publicUrl: https://backup.minio.${DOMAIN}
      volumeSnapshotLocation:
        - name: ceph-block
          provider: csi
          config:
            snapshotClassName: ceph-block
        - name: ceph-filesystem
          provider: csi
          config:
            snapshotClassName: ceph-filesystem
    credentials:
      useSecret: false
    deployNodeAgent: true
