apiVersion: v1
kind: Secret
metadata:
  name: velero-repo-credentials
  namespace: velero
type: Opaque
stringData:
  repository-password: ENC[AES256_GCM,data:Yh9dBxJpHac4hZQsHzr0zmYl0/vE6+W43lHhLtmEVO5psgvpl2R+OeFPfLVdgDo4VpIcURUqBcIxo4bCTzFddg==,iv:Wz9txNNL3llhGLOnQsd9rh4vHX1LPstooee7YByH8oo=,tag:ZP5hDJjGDkNzXewUYEy1jw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVEdzZLR2VKVFJNQjFJ
        dVZ2Y0MyYjc3RUQvTlhCVnFlQk8wNmFFaDI0Ck9QaTBlSFE3SjNLN1Q2eUxpNHJj
        RkJvRTFoN0N4QTg1UVVVcHZLSUpKejAKLS0tIHRYT0RiblYrSW9Yc2RFQ1BsZ2dF
        R2RoaE5sYkVqeGxrRFpnNWlEMThzWHcKlrQyTP8dbaFaMeY0qxcmU7NbG5x7dNFc
        unfZsC9NON8wG5IRGD2yhPQknIiyj+FiO9oAWgZ6o+m/KJ/2V9vmZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T15:25:14Z"
  mac: ENC[AES256_GCM,data:NaDVDSRmqonTOqNrXg+Q3WdwMac1no6WRgV6967pfdl3QYb2cz+ps9FsF+b3L03Vsxe+0hRTGRYPP80sRNSnK7+T71eID+GSi4u+BmwmWlvo7TvaMuXenH4UXPV2QtbkHM6Irj24UfgrqOBumk8PZK9r5HlASxaH/qVWmR9Poy8=,iv:S43bAT0o9oPFA048qUsA8vV3ae/J/dW1q7JYNFy1+Ts=,tag:hIsn+HHolMGDYaYzumHHXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: velero-minio-backup-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:P7TdPQPDvobIOSMGqX1REpbLrLIQf61780oC/IAovHfzFmaZWfdHFzD/qMQHu3mPZZ62Rl35q/IteiluGa4k7IrxCXhRvrEL3NKFqLoBCbI4Ss2MAhExjHa0ID2vTdPhFCg01kfpMlIL9PgS6UP5hEr9K1HTsBzW,iv:3lsYJhI2Z+BNp23tPS0IudiBxUIQs9oeVUM3UF83/RQ=,tag:QFRr0JAK0fXibaapuLoAuw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVEdzZLR2VKVFJNQjFJ
        dVZ2Y0MyYjc3RUQvTlhCVnFlQk8wNmFFaDI0Ck9QaTBlSFE3SjNLN1Q2eUxpNHJj
        RkJvRTFoN0N4QTg1UVVVcHZLSUpKejAKLS0tIHRYT0RiblYrSW9Yc2RFQ1BsZ2dF
        R2RoaE5sYkVqeGxrRFpnNWlEMThzWHcKlrQyTP8dbaFaMeY0qxcmU7NbG5x7dNFc
        unfZsC9NON8wG5IRGD2yhPQknIiyj+FiO9oAWgZ6o+m/KJ/2V9vmZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T15:25:14Z"
  mac: ENC[AES256_GCM,data:NaDVDSRmqonTOqNrXg+Q3WdwMac1no6WRgV6967pfdl3QYb2cz+ps9FsF+b3L03Vsxe+0hRTGRYPP80sRNSnK7+T71eID+GSi4u+BmwmWlvo7TvaMuXenH4UXPV2QtbkHM6Irj24UfgrqOBumk8PZK9r5HlASxaH/qVWmR9Poy8=,iv:S43bAT0o9oPFA048qUsA8vV3ae/J/dW1q7JYNFy1+Ts=,tag:hIsn+HHolMGDYaYzumHHXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
