apiVersion: v1
kind: Secret
metadata:
  name: velero-values
  namespace: velero
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:HGSvrgXIaHgVWk8DzYO4a+Shbk8X6ZJHz3qRnnFfvzQatGM9fGRaQEq/MX6VDUbqpcJHNyH27IJoFrpz2WFRlztbRU6g2rScZmiZcnWHr9Kkq19+H8OVgQmIugJ8Ucd7KIdMX3tOz951swaMZXkvNtbpNCWtmJvFsjJEccSgJlU9mCrV0p0jeC+6LZrpEX8ATd2mf3dpH95Kkt47Hx6N4OUDS3b2bKAQwgwTn7z5OQhw07Yf9nAe9MPpLGTGr6m06ebn5Wm6X21EYwuVqzGDkpd97mLNTgRN/TLUSEALMBdfqgOnrtM/UvC1oZBCizUUYmnjXF5Y0TiUBd5HtJbvtyT9OIJouKqq,iv:zoxgbgbECfdkBM4hfSKHzduZ6Sw28yOOLI8E8u8l3Zk=,tag:aZ7/eyUOutczuJFdNOeaRQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSzdSTzV0TitLamgrekRN
        Zllsc2RPaXRXRkRRNG91a1RGaUxjNGI0d25JCm16TDlQcU1pRmxoeDU3aFQyUkRp
        RnVrK05yQm5LL3BuZWdCSHhiam1mN2sKLS0tIHloSWxmd0xSTWJiVjhWUzA3czBF
        cEU4MlBpdk95djdIV09yUTY3bkNTVXMKTe9nUdEERL9Pud5P8QFH/BqXK2ZQZLGd
        vr/AesNfR1ArHvVShAHeziHQq/cqnn/lAa+dlqjM4KnEVM4Xncbvnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T22:41:10Z"
  mac: ENC[AES256_GCM,data:QdcESnyOmbLmtPx51/gX3FovYp7gOcGQndgyQLK1f5KVh39HwPaqu7NdGM74ljkq0CJFmbrqG3IQTaDgLEShzsL6et551sN4AC5ULB5OHcAm1vIpcjbjpRLMP7hleZXkoZmuP1hWy4gZA8qtap1g15vaBhObd7alWIwHSAwLikc=,iv:4jpQqCwqkTLQx27rUNQ9gZoFtNbk/7OsQ7MN0KuutQI=,tag:kiLgcaR+28WZcVyVYSy+cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
