---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-postgres-17
  namespace: keycloak
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: keycloak-postgres-17
  podMetricsEndpoints:
    - port: metrics
