---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-17
  namespace: keycloak
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    storageClass: ceph-block
    size: 2Gi
  bootstrap:
    initdb:
      database: keycloak
  enablePDB: false
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-backup
