apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: keycloak
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:fwnTGbmJ0m/TEvh+qu04LmaxEEjW2VVPGJu6BJq/bGCOuqPJJEfktb4cgHZBFSZu5jE/RgawoIbqTNjec5Ovkw==,iv:D6vw1RKERmNBrizr12w72oCakJFxJihHULrWIZdmUUs=,tag:hPlxNfJMBgL2EgI11Nko4w==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DVgZwhbTd+2TEMEkAiZiqEaxuvGFYSEd3ABGwpF0UOIYW+cF/LsbHZQR9WISMYfeE8v8jI4ZkD3sDYt3ZI1/DA==,iv:DpCHATdqaMJXYfXgdP/tPYPuuCKEzmfgjuCGv/e8RPs=,tag:c68S/31DgjmdGRl8mnOq1Q==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSit5NExBVTFybENtcWRZ
        aC90bTM4YzdOUDFqRE5LNGlqMGNVaXpnbWhZCnFla0pwdjllUXlDa3IzdFdiQnl3
        OEZBNUlkZlVIellZbHFvaVhoUWlRNWcKLS0tIFczUFVnblhPVTJqOVZtRytRVGdX
        Wk1FZ0tiT3FGUEFvajQzYnVrSmV1cjQKUQQwYJDISCnj8fH4XRd+MVyzg6IvqzzV
        vWU0rxp9rRariIL52114zxsq+t7/cIjOiuN7l+rllTLaTrR4FWaa2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T15:12:21Z"
  mac: ENC[AES256_GCM,data:5uW9xSJolQcRcR+oA0up4W7D6+BxIbFz8gfI1Fa0I6suMJlZEkQFnXaYo2OhxBDJmLYA5O1Mc7joNxkwVCdFffI2XcB0OwLM5u23LrlOmC5x8wxVbgYGMur5mb8bNNFxH3a6R2XVfYjGnYiTnKtuc3x6U06JTTdsYBnmV2zTtVA=,iv:phe2JGyjevwhnVc2ib/g5C1EDJg4gmWHIbE0vsbIkbs=,tag:Fe+qjmF2QJ0D0GFxvOOEOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
