apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: keycloak
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:Nbi/lWziXMMuEk2NFTiwVWRbzG1AUDdvLqlqSs91TuA=,iv:fnJiRKaCh5eZaKsgLtNabt854Y47Y62V/WfGcCuhoz8=,tag:3pnY0QXDYGa7Rvyk4eVm5g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YcKIp7B/zTC8XMzuI99HdH7ES0rKtBuSrPZZRz3Fc6A=,iv:XlNUN5JZbWeVS6ULn0Yl2IqbLLtQipqG7b9+HxyR9SM=,tag:PH1Y1oMfLr0FeGhISPYaTw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN3g0WFUvREY0dVltMDJR
        WDN3Mlo2QU1NeEordnNya3Fkc0JFT0x5U0VzCmJ2OGdjVnFkWnh0L3FRL1M2eXg5
        QXAzUkorU2doQTNxeHBWQmUrbUxxNkEKLS0tIFN2bUQ2dlpSQlR6d3p4VmRKbXpS
        RjBBaDZrMHpnV1NneWZwT0ZWVXArdmcK1fM4tig1R66kRKexZ/oD+BvRcgTESJDd
        QQGAAWRVM1Gyzl+0iuUXLGxQ5WLyzIvoDL0Jyxh55oUbV1yediJIQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T15:03:37Z"
  mac: ENC[AES256_GCM,data:osrepZxRlphSs5nQYKgOdjQUX07G9yfNvFScbSaq27onOo8E7cqDp+lF/kGzw7+BDF80ZA+p5Yrr36KkCI99Hx4Iqyrkyz/EnXhvx7rCKwzxF5BD3h1VyE4uHJ0ELt6JJV8ifG4vSjEv3Nkb9Seh5hAZOCQt7BgyDkmljYEHPlo=,iv:XHrCwQKCZtFRja3iooEZhCWGIqjtGcFnyvurEQ20m4E=,tag:D6ms3tB57gnXJ/bGFbJJoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
