apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: keycloak
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:7A9pR4OZPN5hZWV6raFJwaxyacVfQ3KcXcDlIPgUQhlfRn6unQHlcZ9tz6YMtE8sCC4o0Mo/tsy3ZHvz6+Hlyw==,iv:DYhYEXhJVoT/UOlsc3/YxzLd5bacjLu9R9ilWG67MEk=,tag:xpYm5rGM1YW8tSww8iwrIQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:UOWSQmSLE38WWzhNF8vnYVMA4O4Rxii5E1beknWSHlWCoDuUG2kvHBJKS/tZ9POZeOgK3KwGNgMcSVYqbovFLw==,iv:oMb2DmGJyEFgft7eLYC4dckxHh/MIqte+w/suM8g+AU=,tag:PAAvLoRuur77sJaF5PgvQA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdXQvMWk0aUJsRWJ1QXQw
        anJKdGcxYVVyY3pvTDc3NWhadFJ6c3d3bkFVCkZMUjRBbVlhYVVFTXEzK0NYdjI1
        RWtUcFY3aUoxS1hsclhkNlNNd25xUTAKLS0tIFVEWFB2UXZpdno4YWh3cDhzSWhX
        U1F4S24wZThPcjN3dy9RM3lDUzRiSncK8UdwGW73KiYlxHnZ6llQwrpQafT2+n81
        eBjFSMYYTQ7MuNAoQR4Fdj7pp+2g4SrPpGnFi2I0x0vVmY2mrcyI0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T22:32:45Z"
  mac: ENC[AES256_GCM,data:L4KynVPeIJU3AfUjgwAkladoNHI9Yrwv8fKgrtSedMtXCw2LoeJ/WQnR7S6RdB3uDN7jjybbxqfAGAyuFJ5jiP/SzSI7kyBVuMHjwJrg9o+4YhvmJWESkMj9on1Us8izHANNxKxPGCebFZFJEUERUmViaB6U0eickXR7leIOyFk=,iv:xGfydF/UOGX31yHECMjjYZXwL9dPbUvw1LSctoq8yts=,tag:vcrVnMuu1kDqHbEIX6A1CQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
