---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-postgres-17
  namespace: outline
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    storageClass: ceph-block
    size: 5Gi
  bootstrap:
    initdb:
      database: outline
  enablePDB: false
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-backup
