apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: outline
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:ns5/QkO+BTpYlNnJEZo8FCzMxUtapZXppBfNJs+7ZKc=,iv:HTTuwJp2TmSkehpPfntA09ZOMa8/h64B0eSPjD6FRuM=,tag:KS4R+zPohr4pVSoDp0OI5Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:i2hRxzKWg3JnlretlmnTOytJnvarlgZZBwr7EMH+N+M=,iv:FagQ+4bZ/OMQYCRrzqIln8XeVXbtRnHrs8c6SSgz7oo=,tag:4BmDlLpDbguO9i14Ygy5rg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVWxSTm4wSGduKyt1TkJI
        ZmpmV2xMRnBCOTdoL0dabys4ZmhXd2JSMlcwClRVZGV0TkFwdTJqZUNTTThhbENh
        bXdsTHRiaEZVTVphbE45dG9aYlA3VWcKLS0tIDczRnE2ZmttdjlTNlAxN2dqcXYr
        V0Eyd3FGdi83ejc0dXoxMTk4RjJnWkEKsrnx1P8zqVY9EGG26D9o8iLE3ohDmMlm
        MSTuZWHuQIqqJFdKMZ74Wj2veHg0TEQOISJazHg9MpuQAwJtIGYg0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T15:08:45Z"
  mac: ENC[AES256_GCM,data:qes7rDOYU8BeOFdx5LMT7/+tfhCUhIjrxZqbMrcxHhK2t4x8CbcNLsMkcLLaFFSDIFXDKomVpvwHLHjPmWq9VJc97EnbrhHCw/AOJqX3iCRRj4Isa8VpgNgDN2yXy1cUf3WU48BW2JGyQMLk58NCGRrKRVSswo6pdl0MCYEo+RA=,iv:akpuaNtjhrRMNruI+9Ba0njUhwDuRbjFq00aFfNnHZg=,tag:A17JPoIaIaeNZvejRStx9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
