apiVersion: v1
kind: Secret
metadata:
  name: aistor-values
  namespace: aistor
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:QLmVC5QNUkrhLqk7weDBAARCVxXFzdrl+l87Hx9OVa47Cb+w0QaSsGyz+CbzHKYjf8M2ln43YiCBB4Ihf+yLb1TgF8LGaAezarYskTqov1AKPU8z7teIHcY6tv8Cim31WlEC6/MdxnDXKAm7wDcY9WYANAA2kVCFgj6mwpk7Get/omrRk8pstj1UyLeNRdePLs+1eWhL9zlv8jYIouUxienhAoC0vBDXte2I3vZkdV6eARdgf43EZQfs3+bpAIemDUBTPm/UCD+MyXwZzHb2BmoaQNm3CSSVKC3OyIzBO00AFwfsM882JW5YKUaTkyleYS1Tg0sF5dWkddREQWWQaX+NWxNxx6m7yFVjaRPtsrSjMf3opQv0/7ndfnJegrEuYBGRA8gqV06fdmw+ygxrHjE4edKljvycRo45YWkHvl8LHHAIgTFDE+LGNd/UvhTT9cIpccKJHW1iMZZnEijqs6AsTtpKCOnFe/vfk3cklKWPGFug+o1BXm/D6JYm25xCGmi7E4Tdi1sZ8mFiIrAXAYsGIWpVBF/ntTEd5CtUKA==,iv:DuPwz82CtwVP6ILX5CKSJtFHhEbmhl8wiUazLsuWUiY=,tag:IpvMLAgiu+4m49bu7OBkRw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMnE0Z2g5R0NQQ2lsUWZu
        aTk0Um80U0s4U0IvNXNpNDNwV0FBOXNWcUJnCjYwS25GTjFpM1FaaElsWEo3NlJ5
        L0xMWng0RldJYklnMW1TN2N1L2U0cU0KLS0tIGJ1T2FiVEFJUDVoT2RQNEh1UVZO
        aXNpTXpuSkJPdEwzbGVEbmh0aWtscEUKFmIBCU/rMlAyhJ3VyYl2iLpk7GbP0p59
        4bLwkEH+V059klRE220rrfttUemOLpjVpUeYXwJ4s4eAG7Onf7RsBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T09:08:29Z"
  mac: ENC[AES256_GCM,data:zwQIurVofxVRqNS5+isgFFLflj6yox2O3+xtCEWaUAgw7crd/sSdfj7PhTOjDwxXuHtGyr7Dq1Hxv3HH2BfPH9Le5zv+PezYNXJ0ZCqnKgnA3nYDs5zuoZFHJveKNWyzky5MOWlsV8qgpGaRp/jR40+8BERlQV9+5Z/oLEhVp/M=,iv:YkDK5LhZ2QFZnRLJ7Pvudbvs0yyi7WEvm6W3kb5waik=,tag:t7iew2roFReTJmQ7agqURQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
