apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
type: Opaque
stringData:
  DOMAIN: ENC[AES256_GCM,data:ORW7EnqRXu4=,iv:Xp32+sA8t0X0/vd43dX1HKz8S+2ZhNBdmHJYlbr2Xus=,tag:J0YVu4u2mkqAEmb3YEOd3g==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:j+a53JPx2KpIy2pBJhAl9Q8=,iv:lRMPIPGzz4CeYnZNQJNIu5e+nNw+57Qcr+7AQhLJMAU=,tag:2B8vT3TXHWOrVaP3+Cg5hw==,type:str]
  CLUSTER_DOMAIN_TLS: ENC[AES256_GCM,data:D8kGZN3G6FKwStXPQ0DaqZQ=,iv:qUolkKNMxzVGFWknPHUgpYgKK72hg9eswbs/vyuTbQU=,tag:vmhU/C+CRq8rTfRIi5PJeA==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:ym4GMSDCId2EGw6qYg==,iv:TMBAqBhrh5sdGHBtqczvnEq9c+4+nzxw+xcgiWbp05o=,tag:QHb2KzhJMa1eftkG5SLHkg==,type:str]
  CIDR_SERVICE: ENC[AES256_GCM,data:DeuKUTX3kNxdLK8w2Q==,iv:zisV0wr/uTzCMo6z25F1fWAjWJUBPDX/vCfKwvReEdI=,tag:Fe5H26AdSaZEyrs04w7IPw==,type:str]
  CIDR_PODS: ENC[AES256_GCM,data:wQfqhnJdLEnB2kf+cA==,iv:6AyEJ1NHKeQXybl3rXbf33ThYPRuXdkmsejJ+qo4RdY=,tag:Re1u9ldFKMxqLKWVAHJpsg==,type:str]
  COREDNS_IP: ENC[AES256_GCM,data:ehOxW4/a2QVK6Qc=,iv:ao1rmHPCatLWxdczilSsi5a/i7zTBM5rVek62W4TR6g=,tag:k3OQ5AXOaJ0/nz+sWip28w==,type:str]
  INGRESS_NGINX_IP: ENC[AES256_GCM,data:/I8oIeXx0QYnn4w0QdM=,iv:sCOvEwVcIw8zGmckQoeCDyMVHh7Ma0/+ZgombI8lsD4=,tag:TcGPTFqrveGH+BZV7B4zlw==,type:str]
  NFS_IP: ENC[AES256_GCM,data:lUecpASWDu3GjKw=,iv:Ox38NHGK1o+2fmPOr4bNOZmbRAQ8CPwmV8yPQmcPvmU=,tag:YpXLeKSVlM7vDsaO0DV5Gw==,type:str]
  NFS_SHARE: ENC[AES256_GCM,data:sAKie/FN61bm,iv:WaItjJc9iL/JdpKAM3gRSkbsR+9J9eYJTQR/iYOY/bQ=,tag:rNtYFnuPbKWQHeMLyxCyuw==,type:str]
  BACKUP_S3_URL: ENC[AES256_GCM,data:tchljVgeGDXwJnGJiMUAXsKluBUMi6B4fAk=,iv:9hgUGSWHX2XTgHB8FU5i2ZH16vs8Gn5RG4Ce3RFgMPQ=,tag:+CMb7BR+Y1CFNSbLZQyIeg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dGs2bXRwVGhvNFlGSjFV
        TTJkU3lNNld1aXdnZW1BU3h2dzlxVHBkZVgwCmJwNmdwT3hLWWFBOVJRSkhTZTNq
        ZDVOeVBtdGNDdzBQVWRGZ2Fzazg5ZjQKLS0tIHRmakhJc1NvOERVV0xKcWF0V25a
        Y3QyZnNCOTBrQ0R0allvY0krTTdIM1kKYktSpqK+lueHfJa6Gxx1XMtxCvJbtsqD
        GtY8EvlMWRNeWvrLlk4NbOD639gneOZi4VmgJHudNwj9JIjm4wsu0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T14:55:19Z"
  mac: ENC[AES256_GCM,data:J5PmXGxVDuU9tUyh8Mr0581XMIqgUqG2o7Vt5oaj25MBvR2ianPkFzphr9By9Tnbb9b8L5ForSOwpOmeN1SG9sbNQ/I4VGZGTfZ7rAih7UMQeg8xMLmWW22gYuR01J+iekliPcZNlihFJw6H0tboHKrNZ3N/HfkZmZO6TwK6Wkk=,iv:AjRwFBXtD45NNs0F1I56BuzXWQPpcU4n0UAiaaheizM=,tag:MkYy1V8LJS08OmRI6QeWYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
