apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
type: Opaque
stringData:
  DOMAIN: ENC[AES256_GCM,data:WLhCTy8PAhE=,iv:jV1w3lwXGYW7U5UnDqiscB+upGLiodBeaazXMi4Oksg=,tag:bO3IlE8N6OfSxUHv4XWlyg==,type:str]
  KUBEAPI: ENC[AES256_GCM,data:im0WJT/cJZdN2r8qrlzEoMQ=,iv:bx+ZnCIyNmO3cKPWTe+5w0HrjMcCN3UqguAG6BXzRAk=,tag:oXGh8XuiW42Jjx7gvFuMlw==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:hywQqza8uSMKCDAwXQ==,iv:S2MW/tCGZg6HLYGyxgG8HbZfYG2kiqz5QJD0sy7WYpk=,tag:h3abzouHnk7oj5rHxoZwdA==,type:str]
  CIDR_SERVICE: ENC[AES256_GCM,data:E1gBpNHgjRKerbW9dw==,iv:cs37Ybj7rcH6fZtXnuuI7xfvaXoR14zBj8chCY4n8B4=,tag:lofYsu6xWI0MwbEj4qAN6w==,type:str]
  CIDR_PODS: ENC[AES256_GCM,data:k9IDRvJ+XYd8hEe8dw==,iv:fauLJF0dH/vgK6pN32Kizbz/UzwJcYCLqghU1+2UQF8=,tag:kxfDC8D5tQ7qD8gRdYIb0w==,type:str]
  COREDNS_IP: ENC[AES256_GCM,data:Lb8ZfEEMrakPxkg=,iv:r+mlTaY3Mu9md4OXj7AmRv5iQCUZ8E8j8v705zkiORE=,tag:6QOwIU7HgsdfPM5GgiV43g==,type:str]
  INGRESS_NGINX_IP: ENC[AES256_GCM,data:rdiMEn1jtSAp2PL2sQY=,iv:ehHxKH4v5tBJZ8Z/rICQlTKLolNTyZeHoO9SpzlxC8A=,tag:iX36N/QFLnesN0FPofVD/Q==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWk0WXh6eXVHbkJmalNY
        alJIQklMaUxOTDZCUmllM2hIT0g1cFBMdTFzClRUR2xKeU9BKzJPMnlyekZVMGRr
        VHVaLzRnYzV0b0hDUjNEaHhYajNWS2MKLS0tIEtYb3haaW9nazRLYVRBbHVKOXY5
        ZTIxUWFkaU1rVHZLMTdHOEJkVHczNHMKSl0qVaGryZQvL4O2TBz14x7TnAcy4NV9
        6pLqgopvh1WMifmKCH7xo6Fd5u+4iJGLCgK17vitiA3uFgvTYDTnfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T15:21:37Z"
  mac: ENC[AES256_GCM,data:d+V4PfIhn9XWQIMeXRgi6UqLMGfG5s26TrBBTeltbzxz1f6wNW2HSWnwWNbYqV2RgBEDJyEJEKA6A/vjswdPCVsJa/F/GcIwZfHQguEZbU/Z26REtgCPcdtLpD3FA4aiu06NGW2ePK1s/Ji7Bey9UiuZoIkxqG2HfmpfPi2wSuw=,iv:GTMBJLNTzyMVOmICewmNlGCeXysZxc2tH/MIPx9ZRPE=,tag:10OkJNyGZZtAwUJ5hlYh0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
