apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
type: Opaque
stringData:
  DOMAIN: ENC[AES256_GCM,data:jKzWFwwkjT4=,iv:K7BZgJeFuTNRL5h7jbJkUhEs8SQRo9HDxfauqgfXRjQ=,tag:CN18sq07EQEIemsTDm4TKQ==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:iKXdLSSav+vgMtOYrj+A6Xo=,iv:Np82q/dEFWUY9OE2Nwi1HD38q7pHvbQYzQIbLpstY3A=,tag:Do6O5OOgyeHhYPGz7lYY8A==,type:str]
  CLUSTER_CIDR_PODS: ENC[AES256_GCM,data:7auDUCtbDVE4LEiX,iv:hoDuYCVDHz/bf5rp/vTF1l5jgm+57k7e/iZghgpp5tI=,tag:5KvioC/HZnw/7787IsmUCg==,type:str]
  CLUSTER_CIDR_SERVICE: ENC[AES256_GCM,data:mH12f2F3PdwIffJt,iv:kCX9Hai7bON/wLblgdT2urik0KTrVpHz9iZepl4N0d0=,tag:AF4E63tSGmSYSzEHSsGs4g==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:x7bf+7nLihLvzBMCuA==,iv:5Ym7p0+m/KFZpNhSrj9unWgM8FAo0WSQZWr3Q9TIMGg=,tag:WA4SJEnEWD3OP8SxQBcYTQ==,type:str]
  COREDNS_IP: ENC[AES256_GCM,data:+eisJd/YSdpujQ==,iv:0EA/YG8fs2kDY5QnQA2coCde7wo54cf6FW7C/bNEwXQ=,tag:ZL4pWnpcVQiVkHxg7N9Kug==,type:str]
  ENVOY_GATEWAY_IP: ENC[AES256_GCM,data:d9hFqYQ5JV6gKAI=,iv:B3YKpmdDXQ6/p8mpJPFYsrZ2SBMz2YtZ0+6Ndrc8v3E=,tag:GwTZMGFWCSiPLGSTxRGgPg==,type:str]
  NFS_IP: ENC[AES256_GCM,data:9qZwst7hfaYZpWw=,iv:OMzf4JXRS0GaI3fCVQjw2x5weVUAw1w7VmRyGfX448I=,tag:GrUTlv4fh7dtXXUZn8AyNw==,type:str]
  NFS_SHARE: ENC[AES256_GCM,data:vtY+f1wOcrPp,iv:mSHzBhQgS3z/8MdWg97s2WbT8rgvBTVxbOhSwNkejv4=,tag:6E74l/3P1YcjFG5u3s+j+g==,type:str]
  BACKUP_S3_URL: ENC[AES256_GCM,data:H4iULiq4xv+5zjXjejeS212/,iv:CTq3di08EPZM+5M+ZsKFx+fmPPstt8skxaAYjItHwOY=,tag:w/5saGEm/SbgFONMBVHdzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSHROTEE5eWNaYTc1eStW
        MVBSNnJ3SE9BTlAvM1lXRXJFRStUekF4SUJFCm1pTHlUZC9xN3FIbnJmbE1YL0pE
        YUhoQzVFMDU5a3F1dUgxQ3Q0bGFwVm8KLS0tIFgzaVc5Z3NJMStac1NXNXFodUdE
        aWJMdGxHNk5XRjh6b2gwNUZPNnRkWVkKOVO3vg1qz9LgN4Er+mkZENgBd/Q162sv
        I8mp3H/om7O4AasJ0w216mgBYzed7dcSkQC17DnhCpuFyL9WAlaIqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T22:04:28Z"
  mac: ENC[AES256_GCM,data:/+yKVynYd+KEFiGWC1+d5qtM+ePt5SoEzBD6/PiWiPS633sqbMYEIJdQ/mSKBGDJDtGxzoZf0ohVrHETJbS0xDIlGPhoai0TquB/0AKgfAnonb0Dk0creYzkaYFTmLyMWAsdrVxipFDvp/Tx24SbS35DFrgx7Ut2JpGDsFK1bHQ=,iv:I6BPz1I8z8Z5hqVy+LXk2ZPNywy3U9EjBMY69zd6f9M=,tag:d/PP3wXHVeU+urIxz8qD6g==,type:str]
  version: 3.13.2
