---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgres-rw
    usernameSecret:
      name: keycloak-postgres-app
      key: username
    passwordSecret:
      name: keycloak-postgres-app
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: https://auth.${DOMAIN}
  proxy:
    headers: xforwarded
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    className: nginx
    tlsSecret: auth-${DOMAIN/./-}-tls
  additionalOptions:
    - name: metrics-enabled
      value: 'true'
