---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  parentRef:
    namespace: envoy-gateway-system
    name: envoy-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
    - name: keycloak
      hostname: auth.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: auth-${DOMAIN/./-}-tls
