---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart-aistor
  namespace: stalwart
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: aistor-objectstore
    namespace: stalwart
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    secrets:
      name: aistor-env-configuration
      existingSecret: true
    objectStore:
      name: stalwart-aistor
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 10Gi
      metrics:
        enabled: true
      services:
        console:
          name: stalwart-aistor-console
        minio:
          name: stalwart-aistor
      certificates:
        disableAutoCert: true
      pvcProtection: false
      prometheusOperator: true
      prometheusOperatorScrapeMetricsPaths:
        - /minio/metrics/v3
      env:
        - name: MINIO_DOMAIN
          value: https://aistor.stalwart.${DOMAIN}
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://console.aistor.stalwart.${DOMAIN}
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
