apiVersion: v1
kind: Secret
metadata:
  name: aistor-env-configuration
  namespace: stalwart
type: Opaque
stringData:
  config.env: ENC[AES256_GCM,data:CXP+gn02QnyA3v1s3M+TlHLY9x4+hyBMSJ9U61g2pHAEsJz1dqpWa0cM8/GxrftY4VhjBqSi5s88hUabyp1F9t3HiiQ215ZIto0CfcFDmIJ2PmiDBEA6GQ7SpAqWPllytPWB/hWRYafzRk4x2RTxR0K2q7O5lPvq1za5rfNBQ3lb8uocLz7Ddj/KboRtxjBW2CJZczw5ZNq9A5P2PD2Fz4O9YrU0HOgx6kjtUj2nzuR9l0E=,iv:f8pp0Cb88lgqEf249RbWFK1LDiA4Z3HjO7wGA5ftIa4=,tag:6iCxRg+K9me4+s7zKQTOEQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbHMxem1Ua3UydVcvUHRu
        WjlwaHZIRERMZW11WTZBRmhXWkpwYjNyQlFvCkkrcnplQkRVV2FLTWY0RTlRL3d0
        N2tIYWlJQmVCa3I2RndOVE5aNmcxOTAKLS0tIFF4OTRiekk5TGVTb3JvMHZNMXFM
        S2JjUER0S0lzd1pMSFpHeUVMTnY2NDQKJyTGbhTMgCQY5f9wdREbFIG09A28Xfaa
        IS+3ofIS41oP0ltD5HDzWM1aUf4vJxhvyAvZ4h5ukcW64VbDfPqiKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T21:34:08Z"
  mac: ENC[AES256_GCM,data:kAoB0ehaGPrzwgRY30W9IMNgxbagoghur8XbecWTCP3O1YjVROZ2GQsoH6HN6U8CjtY+Z7Dnw0g+a+oiVxL17wgagxzZ92/QFDhqpPPB/ybMT61tkWFaEYi9dZezssSwvQNeHli5H1Ljz+J+MT7Act9MmI5V5eLi48jw0gcZkWM=,iv:gJCI+LQT3/Skb4w/7ICXZ99J9/+qG7ZdLDuh6xo+clE=,tag:cHF5pMyj47O7OZKE6pUHXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: aistor-stalwart-user
  namespace: stalwart
type: Opaque
stringData:
  ACCESS_KEY: ENC[AES256_GCM,data:WWNtsTcYpbE=,iv:n5oxM7bhL1A52ohYB75WH3Gsf2dS4ng6qrF2JjHPk80=,tag:ImQw5jxUmGDAiogdLPCiPw==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:gVKeSw88btA3Ey0aUA8Kbau1SB54jsE802AxKyfhnBrh8nRXtjzQZzasK/58G9amo0W2o1tJxT96SP7NoRk6DA==,iv:IO85F7j7FWmlaI53mVjPNZGL5Ogca1DsVSGVHC12jjI=,tag:IH1RH/i6EREd0pq6YZUE0w==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbHMxem1Ua3UydVcvUHRu
        WjlwaHZIRERMZW11WTZBRmhXWkpwYjNyQlFvCkkrcnplQkRVV2FLTWY0RTlRL3d0
        N2tIYWlJQmVCa3I2RndOVE5aNmcxOTAKLS0tIFF4OTRiekk5TGVTb3JvMHZNMXFM
        S2JjUER0S0lzd1pMSFpHeUVMTnY2NDQKJyTGbhTMgCQY5f9wdREbFIG09A28Xfaa
        IS+3ofIS41oP0ltD5HDzWM1aUf4vJxhvyAvZ4h5ukcW64VbDfPqiKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T21:34:08Z"
  mac: ENC[AES256_GCM,data:kAoB0ehaGPrzwgRY30W9IMNgxbagoghur8XbecWTCP3O1YjVROZ2GQsoH6HN6U8CjtY+Z7Dnw0g+a+oiVxL17wgagxzZ92/QFDhqpPPB/ybMT61tkWFaEYi9dZezssSwvQNeHli5H1Ljz+J+MT7Act9MmI5V5eLi48jw0gcZkWM=,iv:gJCI+LQT3/Skb4w/7ICXZ99J9/+qG7ZdLDuh6xo+clE=,tag:cHF5pMyj47O7OZKE6pUHXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
