---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/rook/rook-ceph-cluster
  ref:
    tag: v1.19.1
