---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/grafana/helm-charts/loki
  ref:
    tag: 6.53.0
