apiVersion: v1
kind: Secret
metadata:
  name: loki-storage-s3-config
  namespace: monitoring
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:rLrr7XLFNZ0W1FGath+vyGKhrwgDSLB41b6wo10IyrKJUTj/GDV7EuN5eQ7HRUSOZbJ7IneTNPLG1nAoxoamPELWArLTvODuYomQbfPKnCPYFgtHWuEPze28lA6UAwXmJSV0UOZN7cysXYPFHLn6iGbANRb6LRXNpS2OHbMAl+Kntv6W5fPLoqY+MTq2zLAKTmqJznmVE9JkopxzsGq9y6EUHTz1xw4604WMgiPB6JC0hfaeXrqK5URcQYiLZyE8n3Y8AweDv3uzbii9alQXfVO7NNJAVwj4VxvM2wkwngZFVC3kyNefktjzG1zmnYF9rwF+j6Wltn3PKxMpoxbpDlZVj/tlxov9hO3K8k+ANj75qriiUBhCVepDBjT+DKoPX+ucNKDXn1shv9HcAFviy6LPVbzGjL1zxhxkKRwNxjrTtLEY,iv:4XybYuiM54WsiizWWI/SrZ4o9GJJszciOIDlARpTsnc=,tag:qRG738JONHyaS2BQWqXiJw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY21qV2RSL2c5cmkzV3hM
        QXZ0WTRrSFhaYk90WUtpcWg5enNpWHlyNmpvClo0Sy9sTkNreTBHVjMrVjEzcU5T
        R3FpeHZxTmlaZGZUV0JnR052WHNQTU0KLS0tIC9uclJTOExqbTRwc3RlMWk1S3lW
        bVFEZkgzRG1pVG84dXpYWkVmOWFhMzAKB/7P4SsKvE/PBgPfALFNL1OksoCXRJR/
        NB22cR4IscDGg1qqhSlJjvYU4V3QPpbQlW5+Lgajl9xxY12eDsOvdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T16:06:24Z"
  mac: ENC[AES256_GCM,data:xFiLsqPPVm2Fm9VHkgnK+R8LLeeIH/zRKUiyhe3Ec7GMDjrsxJYtBDDypzeMeaV43RXtXcysmqoXl9DZbaFHcwmwasiERPMAA7Q10jxEdFJcQZxKTVJwVRd1mciGoSKnzYwYYvBv80s2WE/VF+buoMArsAS7wpLVeeGkXG1Vt7o=,iv:lLuJfTJc/Jg75KnzZYmNZ5BHfjB6xbC5QE7Wa/PXRlU=,tag:wq3zkw26jJQjkMafm4G79A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
