apiVersion: v1
kind: Secret
metadata:
  name: loki-storage-s3-config
  namespace: monitoring
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:yjw9XesN5SM8/SPxmocap2nnDlzKQUEmKDEsGaikb9te8heaoSjWfXIyPxIJBXjaoXqZmI36eyIeUhlFL8YeUR5rsEdt2+JykWI9+TMC/AlmajFC/HSDM2IR0gpsOJayd0ietWXnb9ekl4iYuSmC4vGQQZck47CRhXir+QtpXoxHTpxvfGy8erVuyqBPUoX5GMG9PzuGPhTjGIE39xy1H39J2qgAS+iTIj4tBN8k9ryQs1qD2Rz6uFY5KStISF9rGMQb8ZmG/PTRuHvrWofz/L2c6SGlda0DfCWl0HE=,iv:xNJe+EKlue+7hR0j/7ZDGuFcLgU/67pSrw+5ZADEoFk=,tag:KGD0CpcblGYXOvkQd2masw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V010OGx0ZFpXZmZsVlV3
        UlUydXJDRGVqS2FqWE1QWFF5TkNhVHV3YmxvCkpQWEh1YlE4NURaUlRxNVlHYVBO
        KzhKTWo0clp5LzVRZUdYMXIzQnM1M2cKLS0tIDFDem9uV09kY0hrZzVLd0t6UWRS
        UG5QaXNKc0VtR2g2NVgwMncrUlAvSXMKN+rhL16Fv+54s7e3iTxvDIZkxrojTXL9
        +Zo+OEbCgdqnosbMlP0iCqcLpISXBtJ8nN7zu7iRgCaccVJY0qF4eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T16:06:25Z"
  mac: ENC[AES256_GCM,data:e+B2Z0PGBOGSz4SPav1AmeBK72I3muAiT9CO8VNaOsNLrigIg9qEYFseD50x+JhmYKtIe50k1QlvtYUI74nuOuMGjaFL3e+WPQ+JJiVEBUV3IvBLpltFLyUUMpjzJwoQqUio1oNhXPLzPaUyTJPPKVZV3TxB7q/tffnpd3sL3+w=,iv:nDpyGAO5a0qbmtKFmIPvlfqIi3Y5zcwhrjehtA3CjFI=,tag:ojjw1x02L83t9Ca7ITuKLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
