apiVersion: v1
kind: Secret
metadata:
  name: loki-helm-values
  namespace: monitoring
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:4fRdSeR3WqQnRfsYmSEEhIuNpCe2NLlky1u+WkYoxMaP/rtP7WyTRlBP/igfZtnz81Z5se2fRn0QRIcjEQIbUwhBR4aO0HzgQniQNWAYa9C10JR4N2mFLzUu+1idQGMnbS6MOzAm850DDaiURucDJ6YknzaQM09R2oNlR8UQ3K38ZxNM322cXAZed1LyaPeYXTJl6VHG1d9ZQek2Hwc/3jeuBC5pN6OI0kSgkF4xvWxDG0keV4bJdAtYXAurCXjz9CD0p/n5oCztz0GSmezPbFHpQXkC8S4FMvdTxf0=,iv:iRd2aQKdJKOAHobGGcy+NVz3PbZTvTIzxQq8+ABi/1Y=,tag:eGrsKS5g1LR63ueOe8embg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZGlSWkJzNVFGdlQzOWlP
        TWg1REhQUVJqb3hJY1dBT0ZsaFAwbTFiMVJVCm9oZENUbW91MWhHOEZCVDBCQ3VU
        U0JORDRpSEFqSWpwQTg0MGhRbGI0aVUKLS0tIDd0YjJ3dDBWR093QUh2SkZhMmVa
        Yi9hMlFrOXhNUXNZMUhyQkVpWWVuamsKsrqpdqDYjKUQTQp79CuCZmYCSw4tRzpg
        9enmiBesO7ZdbCjJIznyczGaJqkUxh3BWwvbGW5UbMGKNxNext+c9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T11:11:48Z"
  mac: ENC[AES256_GCM,data:TLL8L6407zUpQVLUNxaRRBEG6VPxDJKRuYyAgGeDWYEfCjdPK32tmOCXxbWqWraM5F2bCwbYHvKtqOofKLCvHRQ3WoygbKioc68xFJSI1z3QJc/J5ebmH4z3XCxjqkvMN6MVqkqqBBYiPYYQ+2QPIjxXUdd7X71HSagCN7/tkVs=,iv:6I1XzYvLDnJEq4hltjKLvrBK3Jb41QmP8u2fI9uuHGc=,tag:/ft044OzRyYFkPcIt/bKBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
