apiVersion: v1
kind: Secret
metadata:
  name: loki-storage-s3-config
  namespace: monitoring
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:cyQNlyiLCc8UTJ+U7xaPLODwuelOeQdjada1XvbEdbA9TbLlWKGR8ETyRTTtizBxuP6X5pPQVt5hAGU/FeNPSwFS80Mc/WuTMSgQT+FvD9kChuiHegtYsAZ393guCISER3YrG4PnNHCAT5K4c+KYE7Mn7o8ngfL7xrL2dg2KpuwDd4nWLN+c3cdHdFgxp0BCVbCoKDjNwjB36oAH/WImuLC2Vm9j+0XsoXzhzlW4YnU8I34lfGWGmo/p74AWBMkdlUrO7mkcWm93yNA4+PbdoJv2tbUfiHO60eLbKz67sM8ueGXrQByP1HtAEaAq3XG398SiE9jVj13gD2frEVE3jhP2U+XCZbI/vRbTlGyBq08yvQnet5cBpvtoqWcJRCDTzFJ/21JiXrolnXkuDutAA+xBf2mL9YDYO5QoiHrLfCcchZ8V8sujDQ==,iv:PCmo3t38McPGaRxCIkMy4hmsm38KzYBoYIxCWG5d8mM=,tag:NIYN7nC8JRblvnmmBWtMAA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUJBL2pmTFZYbEh4S1JD
        QUFkQmxvejZNQTdXZVRvTnRaa2FteTU4ZURvCmpOUU51VnQvbjkyMGtEWmJ6ZmU5
        cGxxUXJDeDFKMi9EQ0MwUTJyWk5HTVEKLS0tIEJjMG9DV2xYNGFyQ0htSU1jcEVP
        ejIyZlUxVVQvR28xOW52ZmNrbjBNNUkKAT6VViJ5TJKD/IK2FtNdM8UJDrrZWLWC
        dRgGe9Ov1B2wvyRgRReC2Gmj+foPuN49012jSWKGUwJPQa8ObQYqhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T10:20:34Z"
  mac: ENC[AES256_GCM,data:x6XYT27Vp+BpoiZ/Q+6STKD5Z/qccvHQf5MORoCdKvKN//GWKc0AKSJUWzYLwH1fy/1PMPn03OOwIbODQZikklPyxEZg//34+yDC0AmyvHeAnU/pVlJOqWGcYSzrHwN5TkZmhzOY81aGVbTZ8O8NpqYNlRjPkabhpKcnhoGxy/8=,iv:YutYPaKGOJZ6yCZPyK3+r/KAh61zmyEuGSs13MmVtPU=,tag:dbuDfOXarhCE068InmKc8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
