---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: ocis
  namespace: ocis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway-system
  listeners:
    - name: ocis
      hostname: ocis.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ocis-${DOMAIN/./-}-tls
