---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-data
  namespace: ocis
  labels:
    app.kubernetes.io/component: ocis
    app.kubernetes.io/name: ocis
    app.kubernetes.io/instance: ocis
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-etc
  namespace: ocis
  labels:
    app.kubernetes.io/component: ocis
    app.kubernetes.io/name: ocis
    app.kubernetes.io/instance: ocis
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
