apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-values
  namespace: gitlab
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:hwkiHnRp4SDcBmIcJjdOkL4uJqfQ250MOM5ZhlXj7OLtGbij55K07DoMIiDTsRHm3ifxJxbaWxFuChZVp1StHtdlaJyEmjRbN1oUEC0h/BOI+O5K6ObU3/0Mif2F4Rn942fwVefxLJGGlCHHj9e226JCf9kcxilYPsgz+Qvl9ARkcVz2C5lfbx6dWUpX57HD7iqLn+VZ0FGeMVYDyy8lFbHBK/s5Wwih3QjZKHrvTbM7NtW64r6cPaxK7KZ4wuErCuGSbQvwKz1TDlkQchmjawElxeSS,iv:N+lIJZkfPV1ws83Ru36wve3DExPxfLOIxAJjiOLx5eE=,tag:JesoqtSi+Z5rcM3DDhF3mA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSEJ6TDN2UCttQUZZTTN3
        VmRGd2dVeHdvVXZJcmpOdUR4SlZqQ21SakMwCnpUVHExSEExbllpRXBxQndLS29V
        M1lPbEJoZHNUeDZqVzNVVkxBWVNSK0UKLS0tIHFUeGxXdHRSMGtMejZVcFovU21S
        dHhkR0hTSTB0b2pCaXNWWngwdVJzMnMKtpIuGxiRi/TpJkeeOKuF6IWSqerhq4rD
        OPP39LQITvCDP8Q/AMHlP02o/WdKXWyjVRBhruIGjCcMuBZaIKwoKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:gvIJ3KU3+4q9Iny98WMBwkrivusuY6fZ+L1slwfNKs0dhPKWOq7faj5tmPnoDLcMROaAv3KsRDnDOqRR/DN9RW2SxM6v1VtFTOZ4L7lNKi647o/SOhpkdzCza3gapNb5rHmE5u9ivZj+03FP6mO+zibNnXXHHWtWnzIG5s3DSTg=,iv:x3zvvXWzGP1BX1bt/6m8z2/OiUcdQA1iJryMt2riI6I=,tag:sKyDpp+5Qlqzqe3yKi0IVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-user-gitlab
  namespace: gitlab
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:dm62hjHF,iv:r4ZRKCijRGOgXEk9LHftfYIGW76Bzi3y5c695t+xGrs=,tag:TTZIGS3mF4tneWV/uPMzJw==,type:str]
  CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:rOybGXG+CUTuNXJeaxOkZuY3hfwvB29we68Pz7NEG0veX2IdDp1wunf5ZJ3XwOHY7Fo+vjewVvOtNUZfcQqIPw==,iv:xFzolec6Co6BuzhO+e05M961PV8JvCoIrsy3/XZ2ajE=,tag:r4s3iW9k1yfQSSmvwXBRwg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSEJ6TDN2UCttQUZZTTN3
        VmRGd2dVeHdvVXZJcmpOdUR4SlZqQ21SakMwCnpUVHExSEExbllpRXBxQndLS29V
        M1lPbEJoZHNUeDZqVzNVVkxBWVNSK0UKLS0tIHFUeGxXdHRSMGtMejZVcFovU21S
        dHhkR0hTSTB0b2pCaXNWWngwdVJzMnMKtpIuGxiRi/TpJkeeOKuF6IWSqerhq4rD
        OPP39LQITvCDP8Q/AMHlP02o/WdKXWyjVRBhruIGjCcMuBZaIKwoKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:gvIJ3KU3+4q9Iny98WMBwkrivusuY6fZ+L1slwfNKs0dhPKWOq7faj5tmPnoDLcMROaAv3KsRDnDOqRR/DN9RW2SxM6v1VtFTOZ4L7lNKi647o/SOhpkdzCza3gapNb5rHmE5u9ivZj+03FP6mO+zibNnXXHHWtWnzIG5s3DSTg=,iv:x3zvvXWzGP1BX1bt/6m8z2/OiUcdQA1iJryMt2riI6I=,tag:sKyDpp+5Qlqzqe3yKi0IVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
