---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: gitlab
  namespace: gitlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  parentRef:
    namespace: envoy-gateway-system
    name: envoy-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
    - name: gitlab-webservice
      hostname: git..${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: git-${DOMAIN/./-}-tls
    - name: gitlab-registry
      hostname: registry.git.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: registry-git-${DOMAIN/./-}-tls
    - name: gitlab-pages
      hostname: "*.pages.${DOMAIN}"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wild-pages-${DOMAIN/./-}-tls
