---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/linuzctl/helm-charts/gitlab
  ref:
    tag: 9.11.2
