apiVersion: v1
kind: Secret
metadata:
  name: gitlab-mail-password
  namespace: gitlab
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:m4eVnS2UCT3ydxy8dmWP+6M+Rd7aQt3ArCPYBDeROOaTp8aGZVVGPFcvhWUpoPpMc/VbwhTuwI4FMibH2UAygb9jmKH+L6tMkmNZn4RORI4e2pX4CCOnpfX+tyLHVmyNqo4nnmR1uda0qrPCMRe9gWVMTyusjVP1kFFuxVIFQMk=,iv:k9juRt2oGp7fujdORPaLvdVSukIztOBpy8FiAhwUtO0=,tag:OBSz1NGxZAiYhTB/ZwFlSA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-sso
  namespace: gitlab
type: Opaque
stringData:
  provider: ENC[AES256_GCM,data:GFc+ffvWhT1bac0/0TMsduOvIr9xXl7TZG/msGQSAs9b7XX2NHcMntLxvgC88UvZUs5X1mv33CmlYt3d898tAxwEJIK2OEhXwIBq+o852Hs+d53g3PuFnHXi4lrbaKNCzTM1ZhOuOMMovIfyGZbp8K/wB85E01k+cFG6yPCkCwOzieEsmMMpbpFaRlmlDcxGUAebyPlcAH/C4h9YnmLiNfGmwzGBfgakmXSoZw3whB7eqQR8XZ4fhAMqVfRPmt9kVy1/kWM7/wE4hoLl+S7Y8Ttmoety8bAwXWRplSdzNkLcGr/toW5OitQkqq1flVpA9eDLcC2789PZ1MXUccePtjY/KSCgj6vWSu1lDaqjvlRsKLF4MJ6ej7TSgKBSo6wiyeTYHz8TRm4ytZF8NTFG3wh2FmLukNTDiHsY6ZLih+TLZFGlKr16RsPoKYV4NscHe8sEywqJjO/K6FSGYacgVC6fvVe7+oj0dOd4GZ1JBqlFZeHiBlLK6Z/dPZrxj5r0lsoZghzaYxQuDGLNo7YJ7kwtfE30RIiSWh/MY/O1YqbeNhLYcAbCF//f1qqB0QbwNA6bmTDs,iv:LRBawL032pDsgvlrXK8u3aEM4RA8ROktUfRhvnNlxbw=,tag:/BOSPVZZa+Dou/o03q+QgA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:EstvagSv+vDstcpIW+JTAvP3SZg4DTc94d0+I3nge2U9eES5DCe/RjBedxnNMg60dR8Itq1tmjAwwt8cIEDKsT3suGfWQTiAgRtlTrjX17AKWt4OfytbYPdctIIuoFFMO/bl6sl7HA/F1iBvGmHDoEivdanqKmY0n/2zqsPYat8R6/Aq9wVDH4vLIVg5Fd7OYTa0AjbGF2bNvoxQP2izznoDyHpNW0ZojMT0fEGLcOCPK0VBm6YtvZo1k4O7Gt/eoWZ8NStC/YJRoAWMMYgTN6r4D3yNib5qSSFY7JLF5dS88xVKZC7NzG0qDiuu9PupWLXsxtQq4hCeEvYt,iv:XVKSVd+oQb2qgPJHPu+0R9vAQA3LDgo/OFQpFeWll7I=,tag:Yx94X6LWJWJl8w5J6ePuag==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:fSfRvqDnqW8tWleaUMtnS9DzH67uD1ciS1p8JIbtZoN74VL/GMcHAJAk1g0mYQ1tPNkEBvQNFj4cLqt/NeEckGXPWGqztIiD/2jHXeEEivohaqrkHF8RKgZA7GwY/pB8lGqGwun/Ch+jLNYI+WxEYEASkfY1PUiWHPoc1I23ycrPhqS8VlPlcQXdD7bTgQ2MKqk5Nq0BogBNWY8FS1T9SmIzHto67s7pqgNIdLeEabjJmsWRrygvNR/DgG4r7uM8+xgbn7ItYXhULjrx3wLcH4fYCmIDAn8Qw+aVw4UHKZdxHSWMFxHOuQspxN+asy3cN2GR2zXt4aV8THY=,iv:VDz/0vHxSNDgmhkWbrvdQnKG7fGKXRgLw37WbAMSW6Q=,tag:mF/8TApyLGh8bsmQDblDow==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: objectstore-pages
  namespace: gitlab
type: Opaque
stringData:
  connection: ENC[AES256_GCM,data:UBRzyuCTbh1QhetX1ZT/hmVT0qOHreommYhOUMlVxaPTGAInu7AtoBRlssZ0Lz9xH6dPuP5qtzJ3em67u3RCUPDl0iJ4+/PYy837fojMUx8ybzn/RzB2s/7SRJkNF3ogBetm5JBQpi9oWdufCj4Z3wLMQemiWyDK+fZFdFcTg4oLc3501pH2PfRvpc/EkMzIII5yOl6jczASH+wDeQYoZsUbXszoB1DuDg2nwbShaZHMLOfZq8mCiKb3latFdCj+SymcnafvISAgoFAad8HWgGQKF9WRPSY3gfc1vJOfUzjbZBB+WWLHCYHxTlPanuQrYkNHs6cN1xFY3kKn,iv:JXPjHb0qDx0UmQPsxIrxxEP2j6xhPIBUv3+nTAXuNH4=,tag:t+sRXRHgVcpIbQ1m1EYzzQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: s3cmd-config
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:0E9xGDjA/LmDY0VfkZ5DVMqxk81seh8H9PN5F5eCdG21ptK2FETda36CyKsGhlIC46wxS36+l9G/WQMkMULKCgyMY6aCBwEyEPfhqnd6cNWFxQeD29CW4vQUjzmS2fLZRGUM4soZUHWnDqumju3Ix8YjjrHgFhm1Q2p4Ei0XER6imyyaWGERXxzseyq23BK2wOcekcuYgjDYwuNQ74OxuyY0ahVgCWQZGgiUJAmff4CmHpuyi3uwXhkLeyqw0S7o5AzItXJLoL8Z/mBt2r5N/r8fUhgdcS20UKOC5qeqJN09LeQoxCLyGjwZ8G+ajA==,iv:/6Eb4F4bwQtELMREgt89ZFPMEhhEBf+bFz7hXeaEopQ=,tag:iAL05nPrviCqmiM3G1N9Mg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWxIVTZiQnBjSXY1SzJv
        Rm9PYnR0Q3ZGcFJlZkpHcHpzdkY2b2hjNnpFCm05QzNhQXQ1MGJTMzBQT0l4ckJZ
        MGZwc0ZodmkwTHEyUS9qSXpsVzM2Wk0KLS0tIEN3N2gxclU5VmQrRkllM3dQR1lP
        bm9PMXlybjBPZEN5TjMydFF4NGdoc3MKCGSEWE2L/D7NoxtkGEHaJ3iAcJh5Czsi
        r1m/0Xe1k1/iFm38ZCBpiOe/bXNx4qq+fIvi+CFw32s93nBuz2mdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:48:28Z"
  mac: ENC[AES256_GCM,data:ufx6C49Km1u7K4xVOaWBfRGlO3BMok3TUp8aagWGlfVUIwXZu5RwR/BpAqBfTKexW9Pd1vYAWNZB+awSxlOo/zcYGUg4FAPr/d5JN15wf71Ft1nzq3dYS5CwCfTl45Fib/ic3yZXNnw7w+0c0B2MrTW2VPY4akqpbBgBwxzD0Rw=,iv:wsmOvtd4T49zpTgdnzwUcDx3g4J/VUqFTytzAGphSRs=,tag:Iw3jABlZNueSXtR+qqLlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
