apiVersion: v1
kind: Secret
metadata:
  name: gitlab-mail-password
  namespace: gitlab
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:JQsa64Exdr9PLLPyjqLGD417u0SkeAKA2fPjilr6MEsnYdQ9UEtdDyy4xf709IA8nW8GfMSs4x42A1HH0BsiUJRCoXjNoZ6aXRhAzVk6SKrYhBAb0X5cTztxAy4OVOXuCegPfczeHpaEa2HuteVwDKYOPTAXIIevxDGRN9uYqQM=,iv:yW6gp2Bs27jaloGJxUAdIPGrm8s9gPrQMLgBRNyATq0=,tag:K52iU120aklI9Ooei3oXVg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-sso
  namespace: gitlab
type: Opaque
stringData:
  provider: ENC[AES256_GCM,data:FDmJCVAb7ON6E9cfLSu93sPqlx6BJiagbuMs5dweAdohcCMI36pigU9onk5+V+E6Ne8WOVUQhE6TYny5kGe50DEc5mviKA10wWveCBeGgRMuSA0/Na/kw8fzLHpqCacRpm88ocUK9ahYq+94e2V1pJbKdbOIbvRjQGXAej3aid0FdjJcsRKusONkk/0EyJMyEdKMcs4mJXC+gkdz3lNJpomadubXPjz8LiV+P8QINTDzcEEFRGMdVA4Hz0+hLD7vaqcXecrOKn60Dmnbi5a4MOumCijjBTPmjWpyiX52OwRaLlTy6sJi113p9Eova2+rtSYtJ8OWAgUO7VUgAZN4kyZPMswx+D/+uJh1IAs1ampw6PgHcG6UzVGJB6QrRxHt9/gQftak4eKgKIONiEF73WSRhZLnh0paE0mvqUx7WhKFvZ3pIx+Sxn5fqSvhMAo/oHTpoTQZohfEOMZtgbAaHu0pXZM/pbWpUGUatwhjtR56KTLt3qglsZ0/L3uvO3UoIe2MeOkhcR1MvdeGRW3NTt4jgHwM59kahQAVDKENHbD/LWhmeN3UvSEX+DReN4IXEhhlDRa8,iv:q+XvLIyp53qY9g+VZRQEzrQUhLjls5enbe6Q0WPx61U=,tag:slYGysZXkswW0+SEq4pNeg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  connection: ENC[AES256_GCM,data:h73y3n5er3Zw/QHklN2BTZjttr61UmdW7tCmF+zAsSASBt5+Iib3+59Evdqv7vXmijpwRuarQ12ZLrwZx9e7ApizUqx1ReeiNTZKdqK1qpAoO6D/NQAa/gVxZYjmxUAziAW99/736RX5l1UqRwORC+rGl9UlFOczidG0PgbzC9VB7AZp497m54hcTokcNxYXYwYbAnm40Eum3CNb8xY/BlcV/b56TTErCRy/FRTPJhK6k8ON9rSLYv6g4JyUJBoZBcKnTwa4KF83dLMNqKOA+EQw389cwPngUgEvXDlLA72YlqBCaOJYMMid3TEbpzwLFPvZbh2aihvhJ7nf,iv:eQw4GdK4kkBx91qBqRCYZJQ6bE1Zp8EkT5Me4k+PPH0=,tag:1Eis0bwCNJlt97J478bPOg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:qrmJtueCTTmFbuJjJlCr4RQa3JJSXiEgvq36zV3RdNnb5ceezvsv+lGxd57Sskq6MLjalI6dYj3ll6sRF3oBamIeOx5BknX+wYzYOIhOoVbGN2Y/tGKZMasAeSSBOlTFKvQTkgGnNXeqQYdaYM7zMZcSkkwxaLWISSxu/1oslduX7uuN97Fu9U84oUB/AE44OX2Ymg3xFvTh/CC8YMoC7oYfqdshELf/Dw0fnS+XlzPadalPThNxgwFvNkfFixW1rKy7Ultxbv16YQ03tBgjQnaP5d/xg2a2ws8FDW6J+LS/KBhmY5LX8MsXsPQ=,iv:jULRcbSljV/EvOJqTn7TuFAewE42aqYMKdqKu2M69Rc=,tag:IOPNEOuhUvTDDFszSwwFAg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: objectstore-pages
  namespace: gitlab
type: Opaque
stringData:
  connection: ENC[AES256_GCM,data:OShubfzLLxhy630DUUpUTGI4py2LV/FilFS2QjMPLMWhdUihcj6I9XmSp/9vVMA0oWrBNbGtpUfpC5VfC56fMLtKXcpQAZJkV5gmEDGqoCMtZ/xgBOzp15qnIawMA1BUpggpMk86VkRN7aOhYujiMhxK/qwfDTibqoWqAZZQiqSZJARngT4seKEM5sR/0t2NUuwxOgh5wV1y8fqVirqqxh8uBxy6KqpCLQFsJ3XjT1+NdlZOseMQj8d1ETlJl7rJMjLd4MCcii4ZJHLf6ahhh6SG84nmu7jgeuaAlBl6Pl9fjQ5odb5v1aEfBmMxP3y8J+0q6+0yE8vqfMR6,iv:lmwu8hm9jpHpwN3RHMlZCGFCpnhlLVCdtHhyEfAuVV8=,tag:rNuJ5eSvMyuugwVz+Ef/pg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: s3cmd-config
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:tGrwrolACMJyRWFOiMTs9YoCpSwEBu51DYJ+fyTBi4FZsU5ejeXp6GzhLkuT0/M/6G36TwxeQR/RjBdZ1CBssArrjKPqaU6L116Vhjv0rqBg9o1Kna6w/VGQvlcRaEs3vrJuCWBU6DcvNEyxOgduwmh00QTpx5++mCsE3AV1BvJXLKX8t7sbR3QWEr8aH7bRFDVQqVzzXEAncFiIm9kHBhLuvDuX8NmlhQMnTAn2FJYsUolsS6xykN3uikrpbX3+hVxVYTrMOFG7IK67F5c3vp0ffO0u+Uo7uqyoMGg8+pYUcae6bluKGpLPdQOs3DMCTDrCsd3FCxZUFl5DNbLnSGUz3tNO8jJpmGtpBIA90gTkDtrVOtieK2i5vzcMCHMCoy27MxtdiSVUL8s0Cko=,iv:eOEdhRMR8qY19HMRrYdcX/EWkjKjHueEMU27dtQggeg=,tag:LgIg8ZTaMiIJnLW9DzmRHA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXpmc0cwT3pDQkdJQmM4
        UmV5ZFNsV2crVncwbkdWNlhiRWRUWTc4cG5JCm9pbUs4ZWZMWmE3SFROQi8zNi9l
        YjRmQ2NEQkdCbTdyWnJvUElPcDkyS2cKLS0tIFAwZDJQbkY4YjFwZ1FNRmZ1WTdI
        Nm56c3pzR2dzdkNWR1I4RXdOdDJoMEkKdjmcKdHEp3KSRc0IP+CWlLX0cMyhpU3c
        LGTcJbK7HC3h94gYMrPM4FK54E+OPDuzfxcX4EgjdaMk4iRnq17MQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:16:54Z"
  mac: ENC[AES256_GCM,data:qCSPss6VOK4cRvy3HnI2TnETqxXbXo3O84flPRhG9RK4iFDm/ZNGc0BdeyX2KH231QsxEpITcq+6OFx/wPSGAxc+wq2c+2vY2UEm/f+1EnXSgBQuZ4impk2GfgcHkWi0xZlPThKU5b7qX2RVa/vZwB7atkN/LzQ/ifNjO3WbF64=,iv:JsB3zvrumT7ujrKhKVL49xCId9uZnnHf3BUEutaXhzg=,tag:ymBudk+dYd8I5z0ekJCw3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
