apiVersion: v1
kind: Secret
metadata:
  name: gitlab-mail-password
  namespace: gitlab
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:80WysGHxrhM+XaUKuhogpY+bIW6ponqFzgO7kMkpodMH/jxkL4EBTYJnEW6u1YTSA4L15Bk5JeO49RZ33J3Tqv0tnr5Wb51Wof0b/JIvNpt4VCc/Jux8V4e4DrboyDWA/qT66AoOQ3BkLEAD9rdLYHE0SgDf+CSaiHkGVFLzMhg=,iv:7HoX2tERWrMroGsVJdbXOTgy1lQOU+d6GwSCzJgPV5w=,tag:e6UIWM6VP93UMnc1c9ry4g==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-sso
  namespace: gitlab
type: Opaque
stringData:
  provider: ENC[AES256_GCM,data:KYVF6A7K1tRvxL4diuKNrUNEX5qUTYy0clPv9k/wADR2rRXWQ3TIxXtwDbJRuscdtutkaVqLqomGI15qRrilM/edhD/1XD8m9DvFhnHto0XDigk2QK4cHhP1mkerhQPPJtdIOgL3cS+qSwODDSLJZlLdfr+oSPovp5geCg/3VeUXO0YewqNcYWOywhhgQaqkmOrXiW5kqy0g0mEKG03dubToT0hbaPEJEEkZ/p8CzbOI/7268zQ0m8hI6jTkD4rvDhrq4qejMIqkpnIRBy3h+t5NChWCn1lW/J074/l5oj+eAETLBBIX2VmlG4hSu1K8GWLw/zBvXCs2gfISbLkSNpHGQ6Wsrh8VYXYbAWLcZoWWD4g4k75bx4hX3T35+KrhRpSOW6wtIDJIEKjHLoEoTAiFxji+G9goVy1WgeXo1u67+qbmymIz3DAB+8zHDsLcfoBUcpnZBsAJO5hgf2KfhvgvxDCorBPccWuzkJWyRo/RS3ll7xGaq/EbY4uJGORKX2Bzz1VvGhyMcGoaSIqHHAjDVEJoNg4FMZhAloZE0rLnbHEhR8FwNxliO2eX8fjWM0cvfpr+,iv:zCO+1tTr+qTD69rUDLEXfV+fOVlGGJt0Lz0T2CV2yts=,tag:Lk8d96SpO69Kz6l8uxI0uA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:2clckoXFXBVnow1Z5JADg7eO9kc8nEG1btctcTxbRXQXjLwjZxnlltqWB5y4IfN2IUWj5giplmxgx7d0dLTnt3m/Ldl3ejRABU6AW9urhvKwXluUClnJCow1CHJihvSxviujW3KfWLLoP/H8ZBumOZxxUQKvyNA37xlgkhD/9MSvZsr8kSkMl8t9B6Hz9tMBm0MAg3AdOhmg9hHTa8MzVevtWg1AW4amDSRJcPgqWcrJYnU6hIHI8OYk22g8Qe+ftbiq9euq3HUcCCRMontPZFP3LJ8eNkePgEw1QBtd0Ut7mLmuSCfDz32Vwu5/uBh1JsFyL/mYdCw1JiT+,iv:gZiuV5FtVdim6RblJJRYaIZ8cpHK8/o7sKzPfjOC0NE=,tag:wnb7Tjz3fBePY4fpFCtxRw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:rNZalE/T1q/5apnTXJ7LRbVozzH3fGxAyF4w2hDPVaJQENRMKXRw1exUgt/4dNqzZgwBfcXsPfPpVqW5xUzs9UmeUuKl9lUEoGCwF2CzPtQ3LgCnEIBaLjZ7TUsqhddlVqUGhlrOch8yjW+gwSrnZTxS1b3q4JND+WSDH2WsMpSWKmpCPAmPvmZ+F8LLl6TGi4NWRpTO2ln1cq/AgeaMK/I89lNUvO1Cu9e6wDumhS+7DAB/rnUApN5ETabdn9ofQV5YMOww65Tgg/PrjawWv22yO0OPcmNFqN/eQyezgczR1/+We81A50SNBtDmsicglMZbdm+OYaypfL8=,iv:rTX0rA0P2vPOji4oNZRwaFsHC0MjpStA1ZdLZIhoK44=,tag:6UHjP9bX70ew/QbtbugyZw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: objectstore-pages
  namespace: gitlab
type: Opaque
stringData:
  connection: ENC[AES256_GCM,data:B20mQnIZhktkDcEDW5tEqh9uPVVjwqT5FMLajQU09lfl9+GCbYXebRi/NqXCCR4/F8nnr6M4PCqdwu5HjSSba9Y8QMQJ0h86xtj4O/Py39+yCjo+zdQdihOYW+VU+OwrTJyw9IUyxi+1d+LKCLsaW3FNifZ1TFkxHq8YYwKhLiGYTbdbCC2ZpQ80Kop8nQHMeGIJm4HuUF2tRUfX5upRBUCJy/gRb7hIWVtHuuFdsrZMgCPJFtT0D/eWBBvFW+WWP6q8HhE31ag7eamIReXOgqDEknsU/yKAUVWRLUMtN9CyGRD4x4mi7IB8DbvoC6ekNjoZXUawXycqA1Wa,iv:dEIB0PBkpQhRKVhkQOT5eB9TAa+9T+NPkgIrU94HL0k=,tag:lGBcn8SMlWDS4vG2cP3o5w==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: s3cmd-config
  namespace: gitlab
type: Opaque
stringData:
  config: ENC[AES256_GCM,data:P00K2BJy8FZY3BKGFNUMglESORkSLuovoK2Lx1BlrIkESi4vmqLL9+ir1MOeBxcjmETLWRBvAjMqu90LVDrfimG2GkuQHht0VZspUNqU1fvT68CymGwfdAoiOnMrgIQVW9p6Ehtzxxgm8sDVxFPw7GrNSEU2rfMjjBrt1vFOt/AFcZ4nb4X2G7gv8yyNAytf9VddTQS5nCiRAtmQhs0CLMcihp3GyeRWD+Ui4oCMltzoi4QXKHKrfybXTyYKiADiYV9fvA/GBn3rI7I07zqTgGyIUREUa4J6/ufjcJ0C0Iemf1E0nF1UeerO3iIlbGBB6cJZ7yNOeweEFsOqtFQEtmJX8zTofQxgHJRbOFgm4taQgH6MoJADjmrhG8MpSSL1Vkm+jWKGqOtTvimej7I=,iv:aEXvCxte0OaCkP/A3pqH5fpiKCUPzs/1xz40E7YZ3EQ=,tag:+9DolHkVxsUVD8jeP2rVnQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHRSMnk2VXMyT0RFYVpK
        K1p2VEpSSnBpZkxWK2pMSWYzdWF3eFdDVkJ3Ck1KY1JsUnlZM2JTaks5cmtvZFBX
        cnNjTUxsOFgvdFZuYU5tMG1jWWtxVFUKLS0tIEYvbVo0ZXpCV085R2txVkIwa2FS
        Umx1MzNIZTB2RXkyaWFlejZOKzN6Wm8KYgC85y/Qcwg/DFnxyoyJLXMdtkWl4zwG
        DXhLurGgVmgwmcAY7czXDKYl4MpdKJWK7Z6Nn3IdPl9IOjdo5GDUDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T15:38:32Z"
  mac: ENC[AES256_GCM,data:J48yZNvQ6JqqSX1FKxAd1AT2mo989dlIYMuPvVqjoVNTXBU54auGjvSO4XxE3bKzYvQj4H0Mv3wfL5Oy6i6vSFfFlqq1POJ2NTaMf37SdIG2jDI4IfsPQvfwC3YXOVhaR0HmYJNARrLOJVnuUkyQbmhF2oWuXaClJ8n2KEIkz+E=,iv:NDXbG+CxSP76eVLnrbnZsH0e6SkAsXVbBvHJyUs0BRg=,tag:lv0q9Ldj7lY/3ZlABkfycg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
