---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vaultwarden
  namespace: vaultwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vaultwarden
subjects:
  - kind: ServiceAccount
    name: vaultwarden
