---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: metrics-server
    namespace: metrics-server
  install:
    crds: Skip
  upgrade:
    crds: Skip
