---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: operator
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 20m
  values:
    operator:
      replicaCount: 1
      env:
        - name: PROMETHEUS_NAMESPACE
          value: "monitoring"
        - name: PROMETHEUS_NAME
          value: "kube-prometheus-stack-prometheus"
