apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-token
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:9alg/R6BNGh5uJ7qDHJRmGMs+ssxcSBOLfAW9+CvfGyw4d5pJmMn3A==,iv:MixvPMqI7O1G3TosHSYRWlfMbbJEXhzoH8GSUye2N+0=,tag:YLhrFmkmXufnixe6nUtj+Q==,type:comment]
  token: ENC[AES256_GCM,data:uc1wwFLNsQqwJ/4YmLkmYD2vRnJ+EEw3w4dXS6GMvr44Pw8Q5cgnDw==,iv:l/wN71aI9rJV/kVoKuZI9o0iw0Fcx/q3VXmiOdqL13Y=,tag:u/wZ+zudp+mGCu0lobVMOQ==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRmdWdnB3TGRxUDFtZEh6
        VzJOVG5NRXNzbG8xRnhwd2ozay9JR2NCZjFjCmhiUkNkNEpFZ3h1VUJHY1FjT3FY
        YXdEbDE5L0k3VCtaWFF0YW5kT05ZMUUKLS0tIEJPRzFJc0lXdzRLQzNSQkdZY3dS
        d2VlYllnYnU5WnVWb3VLZFBCWUhxdnMKF9I/sGZd1ihIzItlGZdAIbgWz8639qQq
        BuhJBz+Yb6gHSimcqhxC62fzoPON2BQeGaGoRrTWAqiduv7DtHSLoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T18:05:47Z"
  mac: ENC[AES256_GCM,data:JYswzcNCvGidQgtryY/aLDokXAY7H8lxXmVMowjhj9AxXTZCQ8025uemf8tpAzF7+p6W/5qgt+ni2bPTPFexcPOhw+LM8Dag5S4aX0WkrHRVmR70PwwQGsrnuqBi0HsQ3Brf7niuCXpxLXs5MR9khBfqNE+TvwTorvpFwx0RiTA=,iv:5xlrclD1GTRyDqNFqKORPxlCdDGQYyABSF10klSyROE=,tag:MLMXY+1za+Y6prkkKiueww==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
