---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: falco
    namespace: falco
  values:
    driver:
      kind: modern_ebpf
    collectors:
      containerEngine:
        enabled: true
      kubernetes:
        enabled: true
    falcosidekick:
      enabled: true
      replicaCount: 1
      webui:
        enabled: true
        replicaCount: 1
        disableauth: true
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: falco.${DOMAIN}
              paths:
                - path: /
          tls:
            - secretName: falco-${DOMAIN/./-}-tls
              hosts:
                - falco.${DOMAIN}
