---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: mimir-distributed
      version: 6.0.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-bucket-secret
      dnsService: coredns
    metaMonitoring:
      dashboards:
        enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.minio-backup.svc.cluster.local
              region: us-east-2
              access_key_id: ${AWS_ACCESS_KEY_ID}
              secret_access_key: ${AWS_SECRET_ACCESS_KEY}
              insecure: true
        blocks_storage:
          backend: "s3"
          s3:
            bucket_name: mimir-blocks
        ruler_storage:
          backend: "s3"
          s3:
            bucket_name: mimir-ruler
    alertmanager:
      enabled: false
    compactor:
      persistentVolume:
        size: 20Gi
        storageClass: nfs-delete
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    distributor:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    ingester:
      persistentVolume:
        size: 20Gi
        storageClass: nfs-delete
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      topologySpreadConstraints: {}
      affinity: {}
      zoneAwareReplication:
        topologyKey: "kubernetes.io/hostname"
    chunks-cache:
      enabled: true
      replicas: 1
    index-cache:
      enabled: true
      replicas: 1
    metadata-cache:
      enabled: true
      replicas: 1
    results-cache:
      enabled: true
      replicas: 1
    minio:
      enabled: false
    overrides_exporter:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
    kafka:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
        storageClassName: nfs-delete
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      extraEnv:
        - name: KAFKA_HEAP_OPTS
          value: "-Xms512m -Xmx512m"
    querier:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    query_frontend:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    ruler:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    store_gateway:
      persistentVolume:
        size: 10Gi
        storageClass: nfs-delete
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      topologySpreadConstraints: {}
      affinity: {}
      zoneAwareReplication:
        topologyKey: "kubernetes.io/hostname"
    gateway:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
