---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgres-17
  namespace: gitlab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.8
  storage:
    storageClass: ceph-block
    size: 10Gi
  walStorage:
    storageClass: ceph-block
    size: 3Gi
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
  enablePDB: false
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-backup
