---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitlab-postgres-backup
  namespace: gitlab
spec:
  cluster:
    name: gitlab-postgres-17
  schedule: "0 0 2 * * *"  # At 02:00 every day
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
