apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: gitlab
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:BPkBbA/b7H0f95eIRdDFilcXsd3BocT7Wfgv42tKh3HNj264UWR03rVP37DfD/1Xxn3sh0umz0B8g1XXCH1PxA==,iv:ewvI0W7cMM9iilrvpW2V9/zfcziH1GipDslOtzz0u/I=,tag:rrmgGSI5uiHWCPWulg2hKQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:EHa84Mrzr/ZbT14QTMTn64ruo6eSiHwXIKerrMdxhiE4XQuxz4Vh3Z3LhJxsuEL/hsylOxRTpGX0+b2b65Efmw==,iv:DGwJdxxFNsBvuUXGeyH+28wwnspQRla1GkPVYxWHaCo=,tag:wvbDrSEvWHy65KPMnDSa9A==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS2h1Vk9SdHM5bDBqS0th
        ZlV5My9KcGUyajZ2ZkU1ajhld2lGMWtRcHk4Cmt0bUUrci9HQy91dngwNWx0TDhl
        a0hhMWp4dno2cEtyQ3R3WDFKZHFxZE0KLS0tIHJFVm9qSUY2MlNvMC9TU296U2dt
        ZC9PbmcveHlZb0FjdDVQUWE0bjYwaU0KIH+366V6A8P8WYs2J7LEJaTae7BEtJtL
        GGroqIeHFFgSWNjlI1Yp0+vpcGjDR/TGYKnDcmUWO7fVOuEt9FlmoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T22:15:16Z"
  mac: ENC[AES256_GCM,data:wOH/rMqcJ5CCUL+yXT8nCYqJVxNI62O5wyNvJkwVvgvfg1oZHhVNntAop/EZUd9mcRd+M4TgwAFspRhRh+zjQGNgrMMEqxdhCevozvOiOq/oXjmtxahOpNNPBF4pkaS/lHjbaonLMgjIbCFlRc/vjBp6c5S/De5VQ+vGblRk0OY=,iv:9Ye/m2j1QZoyofMBiUiL923RPIyIyxBvgw/+KVM5JpY=,tag:1ULeCG4apdhLaaShhBoQtA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
