apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: gitlab
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:wcCK8RSa7mZX0QLwLDLoAeD7TFyliWgLX5DJtXG2GfI=,iv:DT/UAohiNm/dZfAuhgMbVXtwDQFSS+ct5ouHMy+E7Go=,tag:IBuhL/wfIdzbiossfmZ5Ag==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YXJFK4U+NXSa5dAV+pMuWjM+OKSE1XZt+0Z/kxZwRhM=,iv:tRhbl8hJ2gUmT0ZSqrxTUQFy0h+GCwyjSvMmLozspX4=,tag:Yi29CtN2mDaUUtpGY4Le/A==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRFloU2tQVVVza2lyNCs4
        YzhzanQ3VVZrdDdZcExtcUVxSjN3RFozYUJvCjJkMFE3bzczeDIybUk2Y1R2Uk1Q
        NTRlVU1wNldBS1pnZ2lWWjVvOWUvS0kKLS0tIHNxMlRrTDNYNVZySjlVdlBlZlRt
        N2NxenNURkV5R2RWbzZvYTlJVXZxMjQKyTz2ob6OkqoywNGsHwp+IgyEvLWk0co1
        gixjMGT57ZluQ/8oGa4n19N++CWl0RduUtvtggt/h0Zjs4mzkl7Sug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T14:43:18Z"
  mac: ENC[AES256_GCM,data:065rG9PT5ydm824uTg3yxsVHoL5hzgaLD+rYiA30lE3UJIbSOL0q0MTSYEjUR0j+s/DCV3KJLwfuiiF72UUbtNpOvMQyA4geKTb3633YaJUj6w2ysTzlgQClp0rqYbOtRXMiaes60HWtpzALozuXlTU5M/qmb/Az6JrE7LqxNXM=,iv:HMN8zcxU19+rgKTg0Gu8ondVOIFHJZwHEAVpxz2unck=,tag:RC2xonCAlAq8Cftczqrmeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
