---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: tetragon
    namespace: kube-system
  values:
    tetragon:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
