---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/linuzctl/helm-charts/tetragon
  ref:
    tag: 1.7.0
