---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/dragonflydb/dragonfly-operator.git
  ref:
    # renovate: datasource=github-releases depName=dragonflydb/dragonfly-operator
    tag: v1.4.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/manifests/crd.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator-crds
  namespace: flux-system
spec:
  interval: 20m
  prune: true
  sourceRef:
    kind: GitRepository
    name: dragonfly-operator
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dragonflies.dragonflydb.io
