---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aistor-operator
  namespace: aistor-operator
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: aistor-operator
    namespace: aistor-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: aistor-operator-helm-values
  values:
    global:
      operator:
        extraEnv:
          - name: PROMETHEUS_NAMESPACE
            value: "monitoring"
          - name: PROMETHEUS_NAME
            value: "kube-prometheus-stack-prometheus"
