apiVersion: v1
kind: Secret
metadata:
  name: aistor-operator-helm-values
  namespace: aistor-operator
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:oasTzw8rCl+PPlWzct1WvZDm+wj2XHs7+lUnHmxytrmpsqR0YuZhI7a5o4MXngTfT94FTzaRAh+t1McwXrWNgwO4CpNz9+OQRdWF4A66LuVaqoTmsNJWobJbhrVKfjVTFsHOMS1zNEHmX+P0ZZgoMpmgddYqAz6BxvQDo/4tn0azAhJNBvWmfExSqj0XiAZ+WeM4TTp/Ae1kFIi1f5xH5pa2SouN1GqIi0QmyrXAB1zzwajISrLyvMvzsL5mHJP3og8v7N/XI09mUYpOTx77GDLIbMYgw5u1V81o7iX+b15voYuFonWTUY2Z2N/ILBmUIEDWVsg9ZpU7l/YJhnvmojDcuwXNulfW0m8R74acK2OPewu+zfno95/Cdm9tkWJrhxAwNdYZ6jLvACSzQZ38+b/hvndTmaNw2v+hNpxCkL4KqMW6PlEiOFP4f3eR0uOP6pi202Mw6ghM2ob1tuT/Ld1qwGayBY6ITIB1rkTTUcorXgmIN4ssUJtTrO+4McPHFuybibYaf6m7lLB0y088ZCUSa+LVvv3UiWofN2CJLQ==,iv:sSJpsQOl9cSr3GdIS7Uj5Im934zIfs9L4Mz3u+SDofs=,tag:durMNfAXzlhPSTwBtYkZrg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTjhVbWp4ZmxmcU5vOURl
        dVNjeUxnQnlkQVV5SWlibkhzWmdHSlBJZlZrCkxVZ3VUNVI4Mk5mSmZIMUE3b0FJ
        WlFrSGVLaittN1IrWTVzNGk0dTNXczgKLS0tIHd3d0xZMzV2cUpmQ1hZVzVzdVRy
        amwxMG5mNVVYd2RBMlR2K0VyRUplWVUKPnHw0rdtFvAPq9Wurpt8VOX+70SltFEg
        4MDmrwvnqM6DRpq94HJNf8m00OzWfPYvabapP1QHWQq1l1g+qZ1sRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T11:14:27Z"
  mac: ENC[AES256_GCM,data:z6A/w9Nl+dLufjcJAt9qxY1gOnXRZb6dVbIYkJXKhFBOOar5Y5nst3h/+ColeayNPE87w+Q4ARMg9bkLWn+q+OatUtP86AOwrJzsPXwXIIC3Aql2BzHDHi4opw/8H7l+saLqwOLHfuOiboyOGV13qC/ILPEP1cONHO/OpFM/yQQ=,iv:TBRnm7F6UdNL189g7AaldYFCUzPbAvWj2fTB8xOy9F4=,tag:gXBXz4LbJZxaQnIVw+pz/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
