apiVersion: v1
kind: Secret
metadata:
  name: aistor-operator-values
  namespace: aistor-operator
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:egUka5YcIb8LGzyYkTKi6oUvWIjs8esSBQVH26VR8SryPSd3yVttvNHwaDRsoBuOcFwFNAk9OxwN/PKIs7EFoPEZ9GljGZsAbGTB9sjrR1xwz5owtEdE5j3XRZRftOZYgp1WmZPspt/6a0CPhFpUg3EtIJ7jmapggYcJBGuh1VrguSiyDw/Qk0Qk8J2DeO2eesdoBtUUDLCdxOuT+KxmBEo+nAfEzPLLJbnNXhiNdJrUR/h0kc6sl2p++ql0HLD3Wa5DAluwO0yLKfaAlyl9JLDL4ztQEKpUyWSsBR+8TfHZVO3JBJRlcf7Mdm6RPjNj1DxM3K0f4GtIieskEFBBvN/DBEsi677CmCCfB9cjpYW+HONW0If0z4XWrC6wc4U7jZqYfN+K/XWX8tbBsTB+CDEqnnbz9q/iikC+9LAGloGhO+nZXFetFAe8+DHQR/MUQI3gsJUvfpE52ab3aelLNZPd8Fntp45FbqEI0QAxK0usI7abmFxVRmMl/X/fXApUfrhwcrlryNOWRh5gAlP4dH+KygOZLbhAzq36XJdceg==,iv:FjuteWZXZLTSRkvqF0vecnelsuIE2mjvu+fBdXyHfjA=,tag:P3RRTi6i/u34hT+av8fRhA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOE9hOW1IZk5oN3ZaMzc0
        R3Z3b0llSEJxMDk2Q3NUR2syUzREMGxyeERJCjI2Um1Cei94ajdsR0k3YXY4aVlW
        QTVEeW1Ha1Fvb25WSWxkbUxTL3JFcW8KLS0tIFJIcFV4Z08xNGhudHluWDQ1cmRC
        NnFUK0w4U1M3QVl6bUQ2MlFiVTl2TWsKPPaErA6lQL2q3AMyFMfQ7sB/hqbQQGwC
        EtHQkurgPloJOGPYUyVc0jca8QPXPqDp0O/nKAbGFs1oPpxkLoFUtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T09:17:02Z"
  mac: ENC[AES256_GCM,data:vVaOMP1Gj0oKckkrLOBdAxaB+iHYnmKUpNpZzhErwLLaW955CkzstVnIf+FJeAZcw+px/XqALyaQmYOPNL+pheTIHj45S3u+HwPHIbskmUjkHDy+gc45Bh9Bjorr7+OtH36jEIsgRYKoLYfWOfN7Z2Z0Vtsa/TY4MhciN9zfhuU=,iv:7T3u0kXBafdBua7i28mewnzAciSrdDX4JZdQb7OXTuM=,tag:R2QmO46Zpsg9OrLtnHOuJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
