apiVersion: v1
kind: Secret
metadata:
  name: aistor-env-configuration
  namespace: outline
type: Opaque
stringData:
  config.env: ENC[AES256_GCM,data:Iy+cChyqm7lua7/yyj9/YyATw0X5Uy7O7/5+RT1+tVgVruBTEk6l6VJwJA7B+eCb7SPRX2LCc++f7uUebjKvRDI8OGcwa0o8tcsRWVYc98lyhokU3w1PgUDJOC4WAGNrG4R8Npzel0Mb87CqLsqG+BwV70ZZaG5dI9VaSjdEYHTjASjGzpFeRog4vELZ4aW7XJDvnIFqiO+hsIsc2nZfggxqwtx9Vf8hP9X795BaX0eRXDA=,iv:DjgfYoNh+mggTdf26b3rrWeu5tZp/T6h3GeXfEiQWrM=,tag:YpkkLRRgZY9kr80uE7e/Kg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY1MxUjlnNkRLVElQbnRG
        b1ErdTFSREd4WmFzUkNxUHdlcWRPM1NyUzNRCm9mRUpDaysrTHE1UmhyNEVNNnpS
        Z1pJQkFJQWx1aWhUdHBZN0d0aHhTK28KLS0tIEZaMHZUSlhCOUtkcGk0dUFlL25y
        YnJlTVd5VCtEd3R2d1FiWEFoSXhpd3MK/lmRHau6eGtniSAQexop9KN404tBDM8n
        yiewT/jWyqLxtOGiJ4WFsrdY3eMgORjzq8VHJRtxpxd/ly5Nwt3clQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T20:03:29Z"
  mac: ENC[AES256_GCM,data:GJar4D3L74yuNWQ0nqWAukXZhgpDV5LiADEMOjG9EQk30aM+EM6QoyzbQwh7j9iHuFIx/bcyq8NooVObZCcGCldnjFSu1+K3ATp/R//h6b1li0npBJy02j8sMMquAeE0z/DzOhyw2nrtaWUFejae4rYM4aYxNRP94+Oyxjbf5AQ=,iv:ZfRYhWkp+JXDzVBd/3ds96/TPmKjDVrj4uVH1L1fCvM=,tag:YNHrMU3jq74jPLDGhJ4u2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: aistor-outline-user
  namespace: outline
type: Opaque
stringData:
  ACCESS_KEY: ENC[AES256_GCM,data:g9AoG7hS5a4hfSE6xHg6sqpzA1o=,iv:pcDEvZhel3Zx+HcXpX4bDS0wvsdgJDOtY8G5dSqBgoA=,tag:sbaWrS8yiWZpLsmyZDS8LA==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:p0R9Wtp5tDK0tsHLctkN59sUWQI=,iv:tgcwwbcEpWBiWdsrhp1Tz/ixylvKjsVLOffYJGaHzgg=,tag:NvndVFFuXyj8vN8VmBKcQw==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY1MxUjlnNkRLVElQbnRG
        b1ErdTFSREd4WmFzUkNxUHdlcWRPM1NyUzNRCm9mRUpDaysrTHE1UmhyNEVNNnpS
        Z1pJQkFJQWx1aWhUdHBZN0d0aHhTK28KLS0tIEZaMHZUSlhCOUtkcGk0dUFlL25y
        YnJlTVd5VCtEd3R2d1FiWEFoSXhpd3MK/lmRHau6eGtniSAQexop9KN404tBDM8n
        yiewT/jWyqLxtOGiJ4WFsrdY3eMgORjzq8VHJRtxpxd/ly5Nwt3clQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T20:03:29Z"
  mac: ENC[AES256_GCM,data:GJar4D3L74yuNWQ0nqWAukXZhgpDV5LiADEMOjG9EQk30aM+EM6QoyzbQwh7j9iHuFIx/bcyq8NooVObZCcGCldnjFSu1+K3ATp/R//h6b1li0npBJy02j8sMMquAeE0z/DzOhyw2nrtaWUFejae4rYM4aYxNRP94+Oyxjbf5AQ=,iv:ZfRYhWkp+JXDzVBd/3ds96/TPmKjDVrj4uVH1L1fCvM=,tag:YNHrMU3jq74jPLDGhJ4u2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
