apiVersion: v1
kind: Secret
metadata:
  name: aistor-env-configuration
  namespace: outline
type: Opaque
stringData:
  config.env: ENC[AES256_GCM,data:vKHyH5RbbKQgUk2Xh1DI3GhOUDrHyIktR+qDr4w0yehdf6ZxRPqJbzG4SAD6nxbrIX9ok14JZ7N75lvhH1KRFbAWMIXfigrj7h5eNqdIPaemkQXZP+ZtzT3zAHCyIPktAgocjeUiCws4qmmrC/5UmWctdxhXMMA2yFcHMvK+hz3wAjmsyAPV/8WZPFWiVs1DKRIrOERN6E8+fZF0vWuWmP6yVtq9YWn9sr8gEHCoVyDknJM8mbcvz7YSrWkpDENfy1wtvVaXsZqeeCFYEOX1xMjuGrakE4lBTrfyhZf3NlY6Ens5RhwpnyU0P+8pRkDeJVON8YLrfvGdHEyIH3M+ahi5Usr0QJAc7lrkUzsl3gNqcbVQV8isFex3SzDofZ2LPMNoByeZipv1k/A6IxTp73ugO4NpJpW7aMgT2ya0fS01FptWIdcOq0R4c1XbzbkxNnQGIomRq8AJJljrpNAoF2q9KgTxvSerwgFPZUNTj7T0nT1/fyF/1smL1AxOXm2jTR3ZKMZ9Ei+wva+NaZHfX9PR5GVaQSE7XmMNOKaonMK5pqk/L7LDkKL+cNlDjyO9NMb1bvdwlCZADE33dh5UrxFxRa5Lsvkr8ijFMoaonKxBZOGs13MmDllouPbdmCMsgHdOA0EcDaBjErtGXrnmrjHGb3x4w3UsFmXmqG04A5FD2+Pq8IVXA32lYyr8AIcTnccoe/FDnXheeDs2nUcvOJf26XhG1eXk60BvTr1/X96MpWe2c4ULo67fqH0WWvSFESgenOaQnFUWeu67yKTioYs/oTGaCz8LauV0UGPfEEqjMSmt285pz0rGrWtG+4AEhYiYykrllTA3zIZaopPETwyU8lmOKwQTj+L8zPXDe5MkhJMjtKdzpa4m4Y5JHFGeUcWYyuHcr2i8VqurEInMqsSMyAe9/qQdqHWAOkTKD2QSwcjMLAE1na55cAzEuOjTIQOFXBV3gzKWmsnMQ3jQbr47Eu69QX2Un86zIw7iwFeyN20jLb9HK+Ln,iv:f0pulNUlqrIkEHfdOrR/fCVFx/l+YD/oELs6B7yd5o0=,tag:X/FUZKv4Or2FGZjFELV34g==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV3B3eDhGQTU3L09HcVBF
        SGVTUzFTZm1KT2lPYlJPUU5sQzhaalIzSUZRCmRtOGVkajl0SnFKd2NBUnZvQTVM
        NldyUzRtV21KSEV6d2ZDUWF0bWtKM2cKLS0tIFZHTmM2Tk1Ka1hqRXQrNHlrTXFz
        Wm5BZENpRkMwL3dHT2kranpqRXZDMU0KW7XJ43dAz9QT2kE99m8vJKGpjg3bsLZ/
        OaMsyvR1NmJZvNUH72PqW60DAsIv7Pc2UZukqs13tt0XCvLDpapWWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T12:34:25Z"
  mac: ENC[AES256_GCM,data:czmmEnAVz7BaLGcSktCuF8/G6hHTo+2V9SerevqnYZq2bhdHMzsqBewRhljrU1o9K1W9oC0x5gTi0Cki4q1/zjxI3MI/7Gcf153SmdeXBkWxmlxghYG6q27IDBLwIBQTl7lbxF9d3KxlcAcLEbIfQ78vvnCx2yzetQxpXC693BA=,iv:wRu9S8pro/k7h601hvBf7fOvS2bfWihHH+rQh6v9UL4=,tag:Xl4J1gv+3r/Jru6syCA3Uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: aistor-outline-user
  namespace: outline
type: Opaque
stringData:
  ACCESS_KEY: ENC[AES256_GCM,data:gOK6ucFnJfwLwIjh9mZGLHGTKhk=,iv:OFkOyO4+Nl6Mi7JCz0kBSDBhJZ2ZmxN0PzdDlO2MoxA=,tag:l2Ezsa5MYSnZjXnCt034sg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:b0imu/TU+96TRoa/KZ1CIJdnAto=,iv:A4kVkYCA+ofLxJif/D8EEFIRjIa6E3VVmosc96th1LY=,tag:lRyfi3XXJ8ykzLvGxkxP5g==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV3B3eDhGQTU3L09HcVBF
        SGVTUzFTZm1KT2lPYlJPUU5sQzhaalIzSUZRCmRtOGVkajl0SnFKd2NBUnZvQTVM
        NldyUzRtV21KSEV6d2ZDUWF0bWtKM2cKLS0tIFZHTmM2Tk1Ka1hqRXQrNHlrTXFz
        Wm5BZENpRkMwL3dHT2kranpqRXZDMU0KW7XJ43dAz9QT2kE99m8vJKGpjg3bsLZ/
        OaMsyvR1NmJZvNUH72PqW60DAsIv7Pc2UZukqs13tt0XCvLDpapWWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T12:34:25Z"
  mac: ENC[AES256_GCM,data:czmmEnAVz7BaLGcSktCuF8/G6hHTo+2V9SerevqnYZq2bhdHMzsqBewRhljrU1o9K1W9oC0x5gTi0Cki4q1/zjxI3MI/7Gcf153SmdeXBkWxmlxghYG6q27IDBLwIBQTl7lbxF9d3KxlcAcLEbIfQ78vvnCx2yzetQxpXC693BA=,iv:wRu9S8pro/k7h601hvBf7fOvS2bfWihHH+rQh6v9UL4=,tag:Xl4J1gv+3r/Jru6syCA3Uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
