---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: renovate
      version: 46.6.4
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
      interval: 20m
  valuesFrom:
    - kind: Secret
      name: renovate-helm-values
  values:
    cronjob:
      schedule: '*/15 * * * *'
      timeZone: Europe/Zurich
    serviceAccount:
      create: true
