---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: renovate
    namespace: renovate
  install:
    crds: Skip
  upgrade:
    crds: Skip
  valuesFrom:
    - kind: Secret
      name: renovate-helm-values
  values:
    cronjob:
      schedule: '*/15 * * * *'
      timeZone: Europe/Zurich
    serviceAccount:
      create: true
