---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/renovatebot/charts/renovate
  ref:
    tag: 46.44.0
