apiVersion: v1
kind: Secret
metadata:
  name: renovate-helm-values
  namespace: renovate
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:52yX70iKLt5lhgjrUXaplE1u7Ig4uai9/ieu2VkMnVBbwMLs+pPed3saBPEF8I1toOxs2ATacK4k8WEGf7DhHfTLXt0kxngGfZQr+OqVxDwT697ENtiMJ2lCc/uAHc7xnPVRl7shNCYprJpD5nhOXBc3TqfNKrrl/VIy3GIeZLJKZmZaOxDbtxAy6Gux/gUBIZ+ioN4N8P5nhugB9IyuNnEb30NPr0EPJMUlV5CCs4M3qdOYvu3ZapOY/bY8jbYCcvqvf8/sLD3dUm8kdPKC6E5jaGe15URucpY1FumRjmA4OOXTiw9PRFSamdoi1jRo0zun489Y4ONZ2zmrXHKHzPnp39OkHBhzshowOskaNbx51i67BRSm4VM0AGbwqVIhdeJAAwskXBzERv/QrHnXlMsAysBxg+zXbpRW9lbszZBsoKEyN7mmTUo97bntHhfKiDl03FWrVXFUTriNudn8sdFNciNGANWm79KwdeADCDyfHoAw/+enssZTwc+MsMKwlRAiThsi7wGdJMIleT3Lf6ObCnb8D8ZLAKSUbyzGWLpJUm80c4GFyJiB7OAKIBUxHx4fcDcSCfHj6kzqZmbxXPh8UQQpOlqABJym4pIsRKvF4JvCIJcW7fgnsAhw0jI25T92PUSCfMeTH512Sso6QHkHGAvQNY1WI7L8SXY42FTPskMtXitdfBimS8gguoGocnlrRcZxAWQNYgj7R6fZ+djaD4YmisDxDprFxn25v/xdtBDPWmlpSShQaLctJSo2kuDiCQQ5FVZAkE9oW2Ry4wxl2cc+t0Y4aYD++ujBDWymJbx5e/F9843OjTRSADmtl/sg1U5VswAnIxwCYOeM9UDoa6ONqFK+IbYfI4MMCu8GKOa1WS0nR3wSXZ5AvmNEB6SpUiD8XrG8LfXMpmQE2D9vw+hjK54bJLqd59RhBryP1FCaes3rXGvouMgeIqQQcGSKk5l+0AgNfFRuF+WXXUf9FERY4f0zOFYuif+83fC7WU8e3OJ9rlUoI8Z+S+SxGHLNddMESi4NFaZHffu3uWJL6Bkh9T1dwkn09uV6chs3zVlyeOttFJR4FnS5yPP9W2fUElIzst7oyl98xkK/YJ+rWQyauGsWK6GqAkUYRIaVb4xKDUTIanVxFn4JUR/mNDzbSSMj3axwBP9M7/uKfouOX78dix8xdA9DosCVEFof58xBpeMKtypV528CACWRU9tUuEP9vmJFhDD+1hTMGDTT8D+jucdKxvJMmIp4Pg4uTGuOo1l7JBI7o/+i6O3a7QoZXrYSkbPhuw92R685hhlh3JCOldtbGhjJEyuvHWV9o58wUoKUH6dEtzgp+BaJfXZABAbIpjYOsjzqmTahZTJoEHW7Vvl03LkDPVB+kXMuOfgWoftTxbSWujfzm3F+uSLwibwGO4sAM6kV9ndcNov/gLOiM7CQXt4hOjjrwsoPWgH97oPBwaK/+QsTmxECaXguANYHrN4oeqGPnoxjfGL7f38udOl5EpDjjsAXuGaJYE3ug0FGEK0y1uNa9+/qIQfzI+ROOMGREMHBWjx72Wbm5lnhgwp0dL7n5dkFsJckk/yQHpKk,iv:/dDIAcPaRpuYjSS59RyLQ/qjAO/IP4w/L3fitBqZg+E=,tag:lbONY/p0f2j+K6DTV7lLoA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dWZyTFl3Z1ArdklQbHVL
        NWJueENkYkUvOFZkbnlRYkkydUVaL1VBcUhJCnJxRm5XWS9ORmVPaXREMzFncTdO
        TGhhUE1NN3Y3dGRsSDNuTlVGcTdRYWMKLS0tIC9QWXlGcGVhc1hGOHNHTVBLeHNO
        MTdYajcySG9oNkdtV2hsNjdDcDVrS3cK8GdgO8/kQSxiuCb712fry4x/FeRsAh4g
        65XXdBdCin5ZSy1n8IRUbhnF0Av2YTyVKWQl6JdW909dJT4fw0jbRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T23:00:33Z"
  mac: ENC[AES256_GCM,data:GWNnD5v82/tUZmQcyLeKMUy6mk4o01LaqV+wbXje79+h8T1xkqwS7KLGrenODZYBBmFqU0hFFOJc6eDuaZXvL4UOny8VGwO/rNPt/BnMqmo1T+ESC32xte24B33ze3SyaBflfcri0H0mHRFt7kXsBsDe8dQsqFd4+1jmKxufwAo=,iv:YIihHTQCmqisTytn+VQC56IuJaZa52cXCpYZOhdj7D0=,tag:v6SFgokZqNqgNYvQFSIa1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
