---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: gatekeeper
    namespace: gatekeeper-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
