---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/linuzctl/helm-charts/gatekeeper
  ref:
    tag: 3.22.2
