---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-aistor-bucket-policy
  namespace: stalwart
data:
  bucket-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": [
            "arn:aws:s3:::data",
            "arn:aws:s3:::data/*"
          ]
        }
      ]
    }
