---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infomaniak-webhook
  namespace: cert-manager
spec:
  interval: 30m
  url: https://github.com/Infomaniak/cert-manager-webhook-infomaniak
  ref:
    # renovate: datasource=github-releases depName=Infomaniak/cert-manager-webhook-infomaniak
    tag: v0.3.1
  ignore: |
    /*
    !/deploy/
