apiVersion: v1
kind: Secret
metadata:
  name: infomaniak-api-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:Tm0DSkOKvqbXMVU1e7W1wGT45rYSmoIrrIrmzCHefw+f78OQQw1EmJIbcHos9NWZKmdm5iko6It7EtjDZFALyIA3RHbh2YeQUlryrbRvJhA=,iv:gx4DBOfgyVL4viJKyI9+3mR6rxgEe0KUZyLpbiLGW+Q=,tag:t+jW9T4iNH1DO4NqZEZp3Q==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdG1QbUJzR29QelRnbEli
        TGxPdU5pMzZ4MGNOckFkTFZJNXhuRjQ3ZVc0CjMzWFpUOE80bXJhWDlXVVJqWEVL
        Nzk2L2FkQnFxNllGcW1memhTdnZWemsKLS0tIDNWR2RVdVR0Y3FCRjVFd3paMW04
        N3FwenFCQ2cxK2pxMTBHeXJ2akEweG8KRWqTixZppD/x89wosPoKJJbvB/5i2fca
        MCoHNyLfxPi+coXYLvkmPGHGTPPHGBhTqFyGI3ftDNABd/kP6R2xeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T20:19:53Z"
  mac: ENC[AES256_GCM,data:6gxw04eTzJ8mTWRoHPt+Ivi00ppcgOHIQX5gZM1/3nvcoOgvnRtuoW5RERu2g5y1nJvM5wL2NrlVYn1bkI6tSyI3ubm26cEWsnZuRcyjSaBmUBY5IAdK5e2YZ9SMhMBZ1K4FECPVctyt0ozwNtFFtNSTn+KqGajJ008Esck7Ylc=,iv:masjg6rr+i/428JsLzsWVq2wxh1aBh3z9VihAHuKwDQ=,tag:rNlSvNZulkmpMWWv0/TqcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
