---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/keycloak/keycloak-k8s-resources.git
  ref:
    # renovate: datasource=github-tags depName=keycloak/keycloak-k8s-resources
    tag: 26.4.2
  ignore: |
    # exclude all
    /*
    # include only the specific CRD files
    !/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
    !/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: keycloak-crds
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: keycloakrealmimports.k8s.keycloak.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: keycloaks.k8s.keycloak.org
