---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: promtail
    namespace: monitoring
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    config:
      clients:
        - url: http://loki-headless:3100/loki/api/v1/push
          headers:
            x-Scope-OrgID: monitoring
    serviceMonitor:
      enabled: true
