---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      interval: 20m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    controller:
      replicas: 2
    driver:
      mountPermissions: 511
    externalSnapshotter:
      enabled: false
      customResourceDefinitions:
        enabled: false
    volumeSnapshotClass:
      create: true
      name: csi-nfs-snapclass
      deletionPolicy: Delete
    storageClasses:
      - name: nfs-delete
        parameters:
          server: ${NFS_IP}
          share: ${NFS_SHARE}
        mountPermissions: "0777"
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        mountOptions:
          - rw
          - nconnect=16
      - name: nfs-retain
        parameters:
          server: ${NFS_IP}
          share: ${NFS_SHARE}
        mountPermissions: "0777"
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions:
          - rw
          - nconnect=16
