---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/linuzctl/helm-charts/csi-driver-nfs
  ref:
    tag: 4.13.2
