---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: renovate-dragonfly
  namespace: renovate
spec:
  replicas: 1
  args:
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 1Gi
