---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: renovate-dragonfly
  namespace: renovate
spec:
  selector:
    matchLabels:
      app: renovate-dragonfly
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
