apiVersion: v1
kind: Secret
metadata:
  name: renovate-dragonfly-auth
  namespace: renovate
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:uGfB2stTP7zpfj2DAMHa6TTyzMtrX3jzgjng58ZaHc84VzelcZqT4PrtvIU=,iv:let2OhU4sVI7OZHgL+AUYIm0QE2GjqGdtjyFMyegfXE=,tag:3UbafyDLpoNFoQJEs+BHFg==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY05LVlI2MGlNNitNWnZE
        T1dmUHlkUGljZE1SUUNDSDBTQkwrMitkTmg4CiszRkp6NnlkRzF3bW5aNDk2WlRV
        d09ncGR4VDRMc1JpREY1a092UCtkdjgKLS0tIC9aVUpidGRrOTFYaG1BdFZhN05Q
        K2hHaXZqaENSRFROSk11NmNLajRLYjQKmaJ5RqjDGBS6iwTQqYl0yS/VPgolWX3I
        FFfYSreauyMFWiX2H9Orc+I58/TDZicYlwd6P5WbPye09I3heymkRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T23:00:33Z"
  mac: ENC[AES256_GCM,data:vJhmJb2KkMOAqGTWZMJ6GFnRvIsCxjcioDMayaHlcPqigIIlus5mGGvt/aQ10rMdL905sIPmHExV5R7BqywSrlyWbydlJkDpnveKilgJbTBlETUFXqguS8FmTKdWikg8AUXhkszdhH6GSAvDB6dqJI2swmAV/xwFjEHFxDgYPbc=,iv:4EruH8ESnk/iTNUYSK9bIjoakD/5G6PEyDieDKmDWUo=,tag:4ukQKJS4D/mLy+XVFrizJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
