---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 30m
  url: ci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
  ref:
    tag: v1.2.1
  timeout: 3m
