---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.8.7"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: false
    domain: "cluster.local"
  sync:
    kind: GitRepository
    url: ssh://git@github.com/linuzctl/k8s-gitops.git
    ref: refs/heads/main
    path: cluster
    pullSecret: github-ssh
  kustomize:
    patches:
      # source: https://fluxoperator.dev/docs/instance/customization/#cluster-sync-sops-decryption
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
          - op: add
            path: /spec/postBuild
            value:
              substituteFrom:
                - kind: Secret
                  name: cluster-vars
        target:
          kind: Kustomization
      # source: https://fluxoperator.dev/docs/instance/customization/#increase-concurrency-and-resources-limits
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits
            value:
              cpu: 2000m
              memory: 2048Mi
        target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller|source-controller)"
      # source: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-in-memory-kustomize-builds
      - patch: |
          - op: replace
            path: /spec/template/spec/volumes/0
            value:
              name: temp
              emptyDir:
                medium: Memory
        target:
          kind: Deployment
          name: kustomize-controller
