---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - grafana.yaml
  - grafanadashbaord.yaml
  - grafanadatasource.yaml
  - listenerset.yaml
  - secret.sops.yaml
