apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: grafana
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:NdrO4I7Xtg==,iv:1GN/cV9nPkn9vK9Wlhl4uY3YnNr2ZGlVF08Fe6RiJMk=,tag:nVGN6T42WYOdoV/LNGxWOg==,type:str]
  client-secret: ENC[AES256_GCM,data:yWIkzIPSoiG5W+Hiitt0bv5XzMuGwuNW4e5QfJPhdIM=,iv:r7pvAlzNm0cqtch9tSEiRrIylnoXYGOTXH3zBv7msaw=,tag:R6bVZJ4dc8jKixZftedgAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOTdrMHUrSnJ2bEJuWGFX
        WmtwTzFKWkpZU1V0N1U3S2I1dDhuRmR1L0U0CjI5ZVNBSkJBOW42YUptc2d0NTQx
        MTF3Nk0vYnJhbW9UbVNUWXo1QWh4dncKLS0tIEYrTXQ1NnFpbmlROXBoZ0hTa0xR
        REM3UUxHRmdtZDg4UHYway9uOVdLR1kKmURLx5icWxKHmA7a9DhdihFsE9O/CIDb
        KqbDRdPd9VWULC+MCsTaRRX/2J0Pli7A0KEGvUruw74aawat+Bi7pQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T21:35:44Z"
  mac: ENC[AES256_GCM,data:mFPBe8C2pwpSq8Jy8L+zDPrvH8aNU6JLOVRHSEIDvUKewjHpid5PUkbiipYqrdHjK1xmSGTFo7SC/RaUuB/P5Xb2gDr1b59dP2k7SAI34u9ZzePeRlwv6vbDQV1jvCzto6rfl/G3PMsFFAX5uLDjMlamv4kycMU4jbW1E1JLPro=,iv:pDHT4ATwy7U87CoLnW2K9Z2VOijVp19FuvlrubqiCdQ=,tag:x0sFkDhvZ1FpuOoQ+k9lug==,type:str]
  version: 3.13.1
