---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: monitoring
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    alertmanager:
      alertmanagerSpec:
        forceEnableClusterMode: true
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        remoteWrite:
          - url: http://thanos-receive.thanos.svc.cluster.local:10908/api/v1/receive
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        retention: 14d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 25Gi
