---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: reloader
    namespace: reloader
  values:
    fullnameOverride: reloader
    reloader:
      podMonitor:
        enabled: true

