apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: thanos
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:miCPXVU6Z6qkHw6WrKeD4la1HyF2F0MguK6cU+nPkTtnZZH3eF4atHVuGNoXOfuQytfGOd3up1tdXysWw20LqIPd0tMFWPvh7am0Iw6s0TTg6QD34hMNknXN8zvxKjpYppEhwkgOuZ42M6c01FkFCXZno9HUlWjgiQ/eZSq56pYripgIE/cx+bg8MR61eqZKN/Oqeb8hCgV4Tv6tAq/I,iv:c+p9+An6FfusHcLWo2jDe+/y0ZrOjIS4mRFNNA58eKI=,tag:Dd8M4SbaMgPvf4G8FJ/LAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQWFCejN3U0dtVlFkZlJz
        MGtoK0tNRzJuY3FUcXRhZ25HVmNaSDh5WDIwCkRwdUlGL3c3S1FabmI3Y1M2SVZX
        RndDaWlJY003M2NaOFE4Uk1tb25tY0UKLS0tIGdNbllvTkQ1T2d3VHBCTjFEQzha
        QUhyVUpuYjh3SlVYT0paWmRTdU9QcU0KgnDOCR/ZBqVzq1kRxyzL1snPFJ10Mofo
        4v/ONzZNLV9Cnbe4fOdM4INqnXA9wpKqxepMDfZjKWb1opL+fnfDcQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T12:49:55Z"
  mac: ENC[AES256_GCM,data:02UQZkjHuICpgnYZwo0VhyVNf59rIXTh5x3fPd24Wc91wJthd5Y7hBqOUIICv6gpeDFD1h1MXiEe0hT5PX9AOEAJx4Vvd7O0FsCL2IbZQEvfvETIAgFzeXUramCwwqH5FY4Cpr/lRichehAAtyJCC8FEzYmF1+6HfViutOxABOk=,iv:C1XmHHrZt+AGlmOP/S+Y0omLMLxT3r8H2uCwhfdJgOs=,tag:G9TnAoK2EHFifkcBySaF5Q==,type:str]
  version: 3.13.0
