---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unpoller
  namespace: unpoller
spec:
  interval: 30m
  timeout: 3m
  url: oci://ghcr.io/linuzctl/helm-charts/unpoller
  ref:
    tag: 2.1.0
