apiVersion: v1
kind: Secret
metadata:
  name: unpoller-helm-values
  namespace: unpoller
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:hJP0DsznF39TPWl1e8Up+6PHv07LAMxeLkJdBTeUkD9B0Mo7rf7ur66yGtopaoPc19LUE7wYFzO+YxBULuaEdGwo6Nk3e8QmA/J18HU9KlU7+wH0+46faAw8ovmK54y3qCm3sbEwkE7vfdsskPuVrEYOB6lCuwqBtFq1CwEtCSmrNMcraxF2Pg8qVerDF9KkGhJZAvpH3ML5jLJFMGH9EaVRGdVhSRKGNaho41P8jm3ydofVkkoQwjXOqIyHAATrGbLJI5RcTR+liVOjAtT/SIBB+T3B4EK5GaO+cze1HkLopT5wElSTYN9xlLlbCJhxfhLV8vtaNtEjumPEwKk21KPGvizN7qAUgM4S1avE58DDYF7XwTaQdsNQlcZ1BUIRlKzzXUktRwHFPTCEpL+Dsv8W4NL1xBvMgZb/CUTERCTDHuIHABcZjW4a64OnxBROJTTQcQZ3VVN4hAQtiPpejFHmXxPapv+DrKzVwMD4Sa3cR6sSr6MJepgoj3i1g78nES+bMKgct9zXLI0aHYUR2fesFrdKQ5AitXO7NZ7x5UG9swvLOPhX/SIV9MAcq22w5gqJ1+HJLekWR15K4jsYWheg3KcDMfNURcipN7BRIJA1RcJ+ylBIMutI86LbLDvMasigb75cEOmH2OWYuhk5DfboBq2WQuBKCcG44wSNtNzs0yrV0JsfH3atDFUXY/rPXBMrgLjfeOwujtMFYzk=,iv:JoeM9hIz8tJDjBnHmSayI3Jq2ApAI5Wl8uKTzAiUc5c=,tag:+PUlnUw+OMKVf0aG68BA7A==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcndLTjdrRFR5TjNUZ0Qy
        R1p2U0RJc0l1Sjl2VXBxNWJoaFhwc1BLWmh3CjZ2bmZ0d2xDN0xIbUwwNVA1WERp
        ZW5DN3pLNXpNNlZiZWcrNm4zSjFaSDgKLS0tIFFqSURoQzNMREVHR3FqeWVjRXp5
        cnJIb2dJaWh6MFZzVXdLRFE0cUpoWW8KYC432+lkDRXL9lBYoFiSdxV8OKXDkynz
        cRjL9RL3TIvCja/nFO52e99wpvLVA/VdRHL7VonqoOTuCCbelAo9/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T11:03:31Z"
  mac: ENC[AES256_GCM,data:41qdAAlh/SFSkrtdEEwx0p6p2xWSL7H3K0ce7x1cVJ/ncEb41XEIqaE17GpF/jG5kG2BZ85ILa2iO3XCa8H3LRZ9V+WbDxWSTK6zhiTYmNQDakUqr1K3KlnC/mcJDFKZmy1oSro3Y14CukBIi3T+Xav24G+eezlnwGdY2Y/6KPc=,iv:uoPmSkRMfAkeiqsT4XjnsYFNu5R9oICYYXJ9+ohbJcQ=,tag:ztqBbThE/JSvKAN1dBLufg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
